package currency

// Updated at: 2021-01-05 23:22:11.289779443 +0300 MSK m=+2.577732553
var List = []Currency{
	{
		Alpha3:   "PAB",
		Numeric:  "590",
		Symbol:   "B/.",
		Name:     "Balboa",
		Accuracy: 2,
		Users:    []string{"PAN"},
	},
	{
		Alpha3:   "NZD",
		Numeric:  "554",
		Symbol:   "$",
		Name:     "New Zealand Dollar",
		Accuracy: 2,
		Users:    []string{"COK", "NZL", "PCN", "NIU", "TKL"},
	},
	{
		Alpha3:   "ANG",
		Numeric:  "532",
		Symbol:   "",
		Name:     "Netherlands Antillean Guilder",
		Accuracy: 2,
		Users:    []string{"SXM", "CUW"},
	},
	{
		Alpha3:   "HUF",
		Numeric:  "348",
		Symbol:   "Ft",
		Name:     "Forint",
		Accuracy: 2,
		Users:    []string{"HUN"},
	},
	{
		Alpha3:   "MXN",
		Numeric:  "484",
		Symbol:   "$",
		Name:     "Mexican Peso",
		Accuracy: 2,
		Users:    []string{"MEX"},
	},
	{
		Alpha3:   "MAD",
		Numeric:  "504",
		Symbol:   "DH",
		Name:     "Moroccan Dirham",
		Accuracy: 2,
		Users:    []string{"MAR", "ESH"},
	},
	{
		Alpha3:   "LRD",
		Numeric:  "430",
		Symbol:   "$",
		Name:     "Liberian Dollar",
		Accuracy: 2,
		Users:    []string{"LBR"},
	},
	{
		Alpha3:   "MGA",
		Numeric:  "969",
		Symbol:   "Ar",
		Name:     "Malagasy Ariary",
		Accuracy: 2,
		Users:    []string{"MDG"},
	},
	{
		Alpha3:   "PLN",
		Numeric:  "985",
		Symbol:   "zł",
		Name:     "Zloty",
		Accuracy: 2,
		Users:    []string{"POL"},
	},
	{
		Alpha3:   "BWP",
		Numeric:  "072",
		Symbol:   "P",
		Name:     "Pula",
		Accuracy: 2,
		Users:    []string{"ZWE", "BWA"},
	},
	{
		Alpha3:   "DKK",
		Numeric:  "208",
		Symbol:   "kr.",
		Name:     "Danish Krone",
		Accuracy: 2,
		Users:    []string{"GRL", "DNK", "FRO"},
	},
	{
		Alpha3:   "FJD",
		Numeric:  "242",
		Symbol:   "$",
		Name:     "Fiji Dollar",
		Accuracy: 2,
		Users:    []string{"FJI"},
	},
	{
		Alpha3:   "GNF",
		Numeric:  "324",
		Symbol:   "FG",
		Name:     "Guinean Franc",
		Accuracy: 0,
		Users:    []string{"GIN"},
	},
	{
		Alpha3:   "HKD",
		Numeric:  "344",
		Symbol:   "",
		Name:     "Hong Kong Dollar",
		Accuracy: 2,
		Users:    []string{"HKG"},
	},
	{
		Alpha3:   "BAM",
		Numeric:  "977",
		Symbol:   "KM",
		Name:     "Convertible Mark",
		Accuracy: 2,
		Users:    []string{"BIH"},
	},
	{
		Alpha3:   "GMD",
		Numeric:  "270",
		Symbol:   "D",
		Name:     "Dalasi",
		Accuracy: 2,
		Users:    []string{"GMB"},
	},
	{
		Alpha3:   "SBD",
		Numeric:  "090",
		Symbol:   "$",
		Name:     "Solomon Islands Dollar",
		Accuracy: 2,
		Users:    []string{"SLB"},
	},
	{
		Alpha3:   "SSP",
		Numeric:  "728",
		Symbol:   "£",
		Name:     "South Sudanese Pound",
		Accuracy: 2,
		Users:    []string{"SSD"},
	},
	{
		Alpha3:   "CLF",
		Numeric:  "990",
		Symbol:   "",
		Name:     "Unidad de Fomento",
		Accuracy: 4,
		Users:    []string(nil),
	},
	{
		Alpha3:   "CZK",
		Numeric:  "203",
		Symbol:   "Kč",
		Name:     "Czech Koruna",
		Accuracy: 2,
		Users:    []string{"CZE"},
	},
	{
		Alpha3:   "MWK",
		Numeric:  "454",
		Symbol:   "MK",
		Name:     "Malawi Kwacha",
		Accuracy: 2,
		Users:    []string{"MWI"},
	},
	{
		Alpha3:   "UYW",
		Numeric:  "927",
		Symbol:   "",
		Name:     "Unidad Previsional",
		Accuracy: 4,
		Users:    []string(nil),
	},
	{
		Alpha3:   "AZN",
		Numeric:  "944",
		Symbol:   "₼",
		Name:     "Azerbaijan Manat",
		Accuracy: 2,
		Users:    []string{"AZE"},
	},
	{
		Alpha3:   "BGN",
		Numeric:  "975",
		Symbol:   "лв",
		Name:     "Bulgarian Lev",
		Accuracy: 2,
		Users:    []string{"BGR"},
	},
	{
		Alpha3:   "PHP",
		Numeric:  "608",
		Symbol:   "₱",
		Name:     "Philippine Peso",
		Accuracy: 2,
		Users:    []string{"PHL"},
	},
	{
		Alpha3:   "RON",
		Numeric:  "946",
		Symbol:   "lei",
		Name:     "Romanian Leu",
		Accuracy: 2,
		Users:    []string{"ROU"},
	},
	{
		Alpha3:   "TJS",
		Numeric:  "972",
		Symbol:   "ЅM",
		Name:     "Somoni",
		Accuracy: 2,
		Users:    []string{"TJK"},
	},
	{
		Alpha3:   "IRR",
		Numeric:  "364",
		Symbol:   "﷼",
		Name:     "Iranian Rial",
		Accuracy: 2,
		Users:    []string{"IRN"},
	},
	{
		Alpha3:   "PGK",
		Numeric:  "598",
		Symbol:   "K",
		Name:     "Kina",
		Accuracy: 2,
		Users:    []string{"PNG"},
	},
	{
		Alpha3:   "BDT",
		Numeric:  "050",
		Symbol:   "৳",
		Name:     "Taka",
		Accuracy: 2,
		Users:    []string{"BGD"},
	},
	{
		Alpha3:   "KYD",
		Numeric:  "136",
		Symbol:   "",
		Name:     "Cayman Islands Dollar",
		Accuracy: 2,
		Users:    []string{"CYM"},
	},
	{
		Alpha3:   "CRC",
		Numeric:  "188",
		Symbol:   "₡",
		Name:     "Costa Rican Colon",
		Accuracy: 2,
		Users:    []string{"CRI"},
	},
	{
		Alpha3:   "GIP",
		Numeric:  "292",
		Symbol:   "",
		Name:     "Gibraltar Pound",
		Accuracy: 2,
		Users:    []string{"GIB"},
	},
	{
		Alpha3:   "GYD",
		Numeric:  "328",
		Symbol:   "$",
		Name:     "Guyana Dollar",
		Accuracy: 2,
		Users:    []string{"GUY"},
	},
	{
		Alpha3:   "AOA",
		Numeric:  "973",
		Symbol:   "Kz",
		Name:     "Kwanza",
		Accuracy: 2,
		Users:    []string{"AGO"},
	},
	{
		Alpha3:   "AWG",
		Numeric:  "533",
		Symbol:   "",
		Name:     "Aruban Florin",
		Accuracy: 2,
		Users:    []string{"ABW"},
	},
	{
		Alpha3:   "XAF",
		Numeric:  "950",
		Symbol:   "FCFA",
		Name:     "CFA Franc BEAC",
		Accuracy: 0,
		Users:    []string{"GAB", "GNQ", "CMR", "CAF", "COG", "TCD"},
	},
	{
		Alpha3:   "WST",
		Numeric:  "882",
		Symbol:   "WS$",
		Name:     "Tala",
		Accuracy: 2,
		Users:    []string{"WSM"},
	},
	{
		Alpha3:   "ZMW",
		Numeric:  "967",
		Symbol:   "",
		Name:     "Zambian Kwacha",
		Accuracy: 2,
		Users:    []string{"ZMB"},
	},
	{
		Alpha3:   "CDF",
		Numeric:  "976",
		Symbol:   "FC",
		Name:     "Congolese Franc",
		Accuracy: 2,
		Users:    []string{"COD"},
	},
	{
		Alpha3:   "MNT",
		Numeric:  "496",
		Symbol:   "₮",
		Name:     "Tugrik",
		Accuracy: 2,
		Users:    []string{"MNG"},
	},
	{
		Alpha3:   "SGD",
		Numeric:  "702",
		Symbol:   "$",
		Name:     "Singapore Dollar",
		Accuracy: 2,
		Users:    []string{"BRN", "SGP"},
	},
	{
		Alpha3:   "UYU",
		Numeric:  "858",
		Symbol:   "$U",
		Name:     "Peso Uruguayo",
		Accuracy: 2,
		Users:    []string{"URY"},
	},
	{
		Alpha3:   "UYI",
		Numeric:  "940",
		Symbol:   "",
		Name:     "Uruguay Peso en Unidades Indexadas (UI)",
		Accuracy: 0,
		Users:    []string(nil),
	},
	{
		Alpha3:   "CUP",
		Numeric:  "192",
		Symbol:   "",
		Name:     "Cuban Peso",
		Accuracy: 2,
		Users:    []string{"CUB"},
	},
	{
		Alpha3:   "DOP",
		Numeric:  "214",
		Symbol:   "RD$",
		Name:     "Dominican Peso",
		Accuracy: 2,
		Users:    []string{"DOM"},
	},
	{
		Alpha3:   "MKD",
		Numeric:  "807",
		Symbol:   "ден",
		Name:     "Denar",
		Accuracy: 2,
		Users:    []string{"MKD"},
	},
	{
		Alpha3:   "MVR",
		Numeric:  "462",
		Symbol:   "Rf",
		Name:     "Rufiyaa",
		Accuracy: 2,
		Users:    []string{"MDV"},
	},
	{
		Alpha3:   "AED",
		Numeric:  "784",
		Symbol:   "د.إ",
		Name:     "UAE Dirham",
		Accuracy: 2,
		Users:    []string{"ARE"},
	},
	{
		Alpha3:   "BTN",
		Numeric:  "064",
		Symbol:   "Nu.",
		Name:     "Ngultrum",
		Accuracy: 2,
		Users:    []string{"BTN"},
	},
	{
		Alpha3:   "GBP",
		Numeric:  "826",
		Symbol:   "£",
		Name:     "Pound Sterling",
		Accuracy: 2,
		Users:    []string{"ATA", "ZWE", "GGY", "IMN", "GBR", "SGS", "JEY"},
	},
	{
		Alpha3:   "IDR",
		Numeric:  "360",
		Symbol:   "Rp",
		Name:     "Rupiah",
		Accuracy: 2,
		Users:    []string{"IDN"},
	},
	{
		Alpha3:   "ILS",
		Numeric:  "376",
		Symbol:   "₪",
		Name:     "New Israeli Sheqel",
		Accuracy: 2,
		Users:    []string{"PSE", "ISR"},
	},
	{
		Alpha3:   "SRD",
		Numeric:  "968",
		Symbol:   "$",
		Name:     "Surinam Dollar",
		Accuracy: 2,
		Users:    []string{"SUR"},
	},
	{
		Alpha3:   "CAD",
		Numeric:  "124",
		Symbol:   "$",
		Name:     "Canadian Dollar",
		Accuracy: 2,
		Users:    []string{"CAN"},
	},
	{
		Alpha3:   "HRK",
		Numeric:  "191",
		Symbol:   "kn",
		Name:     "Kuna",
		Accuracy: 2,
		Users:    []string{"HRV"},
	},
	{
		Alpha3:   "CHF",
		Numeric:  "756",
		Symbol:   "CHF",
		Name:     "Swiss Franc",
		Accuracy: 2,
		Users:    []string{"CHE", "LIE"},
	},
	{
		Alpha3:   "MMK",
		Numeric:  "104",
		Symbol:   "K",
		Name:     "Kyat",
		Accuracy: 2,
		Users:    []string{"MMR"},
	},
	{
		Alpha3:   "TOP",
		Numeric:  "776",
		Symbol:   "T$",
		Name:     "Pa’anga",
		Accuracy: 2,
		Users:    []string{"TON"},
	},
	{
		Alpha3:   "NGN",
		Numeric:  "566",
		Symbol:   "₦",
		Name:     "Naira",
		Accuracy: 2,
		Users:    []string{"NGA"},
	},
	{
		Alpha3:   "SAR",
		Numeric:  "682",
		Symbol:   "﷼",
		Name:     "Saudi Riyal",
		Accuracy: 2,
		Users:    []string{"SAU"},
	},
	{
		Alpha3:   "UGX",
		Numeric:  "800",
		Symbol:   "USh",
		Name:     "Uganda Shilling",
		Accuracy: 0,
		Users:    []string{"UGA"},
	},
	{
		Alpha3:   "FKP",
		Numeric:  "238",
		Symbol:   "",
		Name:     "Falkland Islands Pound",
		Accuracy: 2,
		Users:    []string{"FLK"},
	},
	{
		Alpha3:   "OMR",
		Numeric:  "512",
		Symbol:   "﷼",
		Name:     "Rial Omani",
		Accuracy: 3,
		Users:    []string{"OMN"},
	},
	{
		Alpha3:   "CVE",
		Numeric:  "132",
		Symbol:   "$",
		Name:     "Cabo Verde Escudo",
		Accuracy: 2,
		Users:    []string{"CPV"},
	},
	{
		Alpha3:   "KHR",
		Numeric:  "116",
		Symbol:   "៛",
		Name:     "Riel",
		Accuracy: 2,
		Users:    []string{"KHM"},
	},
	{
		Alpha3:   "IQD",
		Numeric:  "368",
		Symbol:   "ع.د",
		Name:     "Iraqi Dinar",
		Accuracy: 3,
		Users:    []string{"IRQ"},
	},
	{
		Alpha3:   "KGS",
		Numeric:  "417",
		Symbol:   "лв",
		Name:     "Som",
		Accuracy: 2,
		Users:    []string{"KGZ"},
	},
	{
		Alpha3:   "MZN",
		Numeric:  "943",
		Symbol:   "MT",
		Name:     "Mozambique Metical",
		Accuracy: 2,
		Users:    []string{"MOZ"},
	},
	{
		Alpha3:   "THB",
		Numeric:  "764",
		Symbol:   "฿",
		Name:     "Baht",
		Accuracy: 2,
		Users:    []string{"THA"},
	},
	{
		Alpha3:   "EUR",
		Numeric:  "978",
		Symbol:   "€",
		Name:     "Euro",
		Accuracy: 2,
		Users:    []string{"EST", "DEU", "SPM", "AUT", "ZWE", "SVK", "ESP", "MLT", "PRT", "ATF", "CYP", "GUF", "MYT", "LVA", "LUX", "MAF", "REU", "LTU", "KOS", "BLM", "AND", "FIN", "GLP", "MCO", "NLD", "ALA", "GRC", "SVN", "MTQ", "MNE", "IRL", "SMR", "ITA", "BEL", "FRA", "VAT"},
	},
	{
		Alpha3:   "BOV",
		Numeric:  "984",
		Symbol:   "",
		Name:     "Mvdol",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "BND",
		Numeric:  "096",
		Symbol:   "$",
		Name:     "Brunei Dollar",
		Accuracy: 2,
		Users:    []string{"BRN", "SGP"},
	},
	{
		Alpha3:   "BIF",
		Numeric:  "108",
		Symbol:   "FBu",
		Name:     "Burundi Franc",
		Accuracy: 0,
		Users:    []string{"BDI"},
	},
	{
		Alpha3:   "MRU",
		Numeric:  "929",
		Symbol:   "",
		Name:     "Ouguiya",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "STN",
		Numeric:  "930",
		Symbol:   "",
		Name:     "Dobra",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "SCR",
		Numeric:  "690",
		Symbol:   "₨",
		Name:     "Seychelles Rupee",
		Accuracy: 2,
		Users:    []string{"SYC"},
	},
	{
		Alpha3:   "CHE",
		Numeric:  "947",
		Symbol:   "",
		Name:     "WIR Euro",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "ARS",
		Numeric:  "032",
		Symbol:   "$",
		Name:     "Argentine Peso",
		Accuracy: 2,
		Users:    []string{"ARG"},
	},
	{
		Alpha3:   "BBD",
		Numeric:  "052",
		Symbol:   "$",
		Name:     "Barbados Dollar",
		Accuracy: 2,
		Users:    []string{"BRB"},
	},
	{
		Alpha3:   "BYN",
		Numeric:  "933",
		Symbol:   "",
		Name:     "Belarusian Ruble",
		Accuracy: 2,
		Users:    []string{"BLR"},
	},
	{
		Alpha3:   "BMD",
		Numeric:  "060",
		Symbol:   "",
		Name:     "Bermudian Dollar",
		Accuracy: 2,
		Users:    []string{"BMU"},
	},
	{
		Alpha3:   "KPW",
		Numeric:  "408",
		Symbol:   "₩",
		Name:     "North Korean Won",
		Accuracy: 2,
		Users:    []string{"PRK"},
	},
	{
		Alpha3:   "USN",
		Numeric:  "997",
		Symbol:   "",
		Name:     "US Dollar (Next day)",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "GEL",
		Numeric:  "981",
		Symbol:   "ლ",
		Name:     "Lari",
		Accuracy: 2,
		Users:    []string{"GEO"},
	},
	{
		Alpha3:   "LYD",
		Numeric:  "434",
		Symbol:   "ل.د",
		Name:     "Libyan Dinar",
		Accuracy: 3,
		Users:    []string{"LBY"},
	},
	{
		Alpha3:   "PKR",
		Numeric:  "586",
		Symbol:   "₨",
		Name:     "Pakistan Rupee",
		Accuracy: 2,
		Users:    []string{"PAK"},
	},
	{
		Alpha3:   "TND",
		Numeric:  "788",
		Symbol:   "د.ت",
		Name:     "Tunisian Dinar",
		Accuracy: 3,
		Users:    []string{"TUN"},
	},
	{
		Alpha3:   "TZS",
		Numeric:  "834",
		Symbol:   "TSh",
		Name:     "Tanzanian Shilling",
		Accuracy: 2,
		Users:    []string{"TZA"},
	},
	{
		Alpha3:   "AFN",
		Numeric:  "971",
		Symbol:   "؋",
		Name:     "Afghani",
		Accuracy: 2,
		Users:    []string{"AFG"},
	},
	{
		Alpha3:   "ETB",
		Numeric:  "230",
		Symbol:   "ብር",
		Name:     "Ethiopian Birr",
		Accuracy: 2,
		Users:    []string{"ETH"},
	},
	{
		Alpha3:   "QAR",
		Numeric:  "634",
		Symbol:   "﷼",
		Name:     "Qatari Rial",
		Accuracy: 2,
		Users:    []string{"QAT"},
	},
	{
		Alpha3:   "SHP",
		Numeric:  "654",
		Symbol:   "",
		Name:     "Saint Helena Pound",
		Accuracy: 2,
		Users:    []string{"SHN"},
	},
	{
		Alpha3:   "RSD",
		Numeric:  "941",
		Symbol:   "Дин.",
		Name:     "Serbian Dinar",
		Accuracy: 2,
		Users:    []string{"SRB"},
	},
	{
		Alpha3:   "NPR",
		Numeric:  "524",
		Symbol:   "₨",
		Name:     "Nepalese Rupee",
		Accuracy: 2,
		Users:    []string{"NPL"},
	},
	{
		Alpha3:   "SLL",
		Numeric:  "694",
		Symbol:   "Le",
		Name:     "Leone",
		Accuracy: 2,
		Users:    []string{"SLE"},
	},
	{
		Alpha3:   "BSD",
		Numeric:  "044",
		Symbol:   "$",
		Name:     "Bahamian Dollar",
		Accuracy: 2,
		Users:    []string{"BHS"},
	},
	{
		Alpha3:   "NOK",
		Numeric:  "578",
		Symbol:   "kr",
		Name:     "Norwegian Krone",
		Accuracy: 2,
		Users:    []string{"NOR", "BVT", "SJM"},
	},
	{
		Alpha3:   "XPF",
		Numeric:  "953",
		Symbol:   "",
		Name:     "CFP Franc",
		Accuracy: 0,
		Users:    []string{"NCL", "WLF", "PYF"},
	},
	{
		Alpha3:   "ISK",
		Numeric:  "352",
		Symbol:   "kr",
		Name:     "Iceland Krona",
		Accuracy: 0,
		Users:    []string{"ISL"},
	},
	{
		Alpha3:   "KZT",
		Numeric:  "398",
		Symbol:   "лв",
		Name:     "Tenge",
		Accuracy: 2,
		Users:    []string{"KAZ"},
	},
	{
		Alpha3:   "BOB",
		Numeric:  "068",
		Symbol:   "$b",
		Name:     "Boliviano",
		Accuracy: 2,
		Users:    []string{"BOL"},
	},
	{
		Alpha3:   "ERN",
		Numeric:  "232",
		Symbol:   "ናቕፋ",
		Name:     "Nakfa",
		Accuracy: 2,
		Users:    []string{"ERI"},
	},
	{
		Alpha3:   "SOS",
		Numeric:  "706",
		Symbol:   "S",
		Name:     "Somali Shilling",
		Accuracy: 2,
		Users:    []string{"SOM"},
	},
	{
		Alpha3:   "UAH",
		Numeric:  "980",
		Symbol:   "₴",
		Name:     "Hryvnia",
		Accuracy: 2,
		Users:    []string{"UKR"},
	},
	{
		Alpha3:   "USD",
		Numeric:  "840",
		Symbol:   "$",
		Name:     "US Dollar",
		Accuracy: 2,
		Users:    []string{"VGB", "PRI", "TLS", "ECU", "ZWE", "PLW", "MNP", "PAN", "GUM", "IOT", "FSM", "SLV", "TCA", "BES", "USA", "MHL", "ASM", "VIR", "KHM"},
	},
	{
		Alpha3:   "COU",
		Numeric:  "970",
		Symbol:   "",
		Name:     "Unidad de Valor Real",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "GTQ",
		Numeric:  "320",
		Symbol:   "Q",
		Name:     "Quetzal",
		Accuracy: 2,
		Users:    []string{"GTM"},
	},
	{
		Alpha3:   "JMD",
		Numeric:  "388",
		Symbol:   "J$",
		Name:     "Jamaican Dollar",
		Accuracy: 2,
		Users:    []string{"JAM"},
	},
	{
		Alpha3:   "NAD",
		Numeric:  "516",
		Symbol:   "$",
		Name:     "Namibia Dollar",
		Accuracy: 2,
		Users:    []string{"NAM"},
	},
	{
		Alpha3:   "JOD",
		Numeric:  "400",
		Symbol:   "د.ا",
		Name:     "Jordanian Dinar",
		Accuracy: 3,
		Users:    []string{"JOR"},
	},
	{
		Alpha3:   "MOP",
		Numeric:  "446",
		Symbol:   "",
		Name:     "Pataca",
		Accuracy: 2,
		Users:    []string{"MAC"},
	},
	{
		Alpha3:   "SEK",
		Numeric:  "752",
		Symbol:   "kr",
		Name:     "Swedish Krona",
		Accuracy: 2,
		Users:    []string{"SWE"},
	},
	{
		Alpha3:   "SDG",
		Numeric:  "938",
		Symbol:   "SD",
		Name:     "Sudanese Pound",
		Accuracy: 2,
		Users:    []string{"SDN"},
	},
	{
		Alpha3:   "BRL",
		Numeric:  "986",
		Symbol:   "R$",
		Name:     "Brazilian Real",
		Accuracy: 2,
		Users:    []string{"BRA"},
	},
	{
		Alpha3:   "KRW",
		Numeric:  "410",
		Symbol:   "₩",
		Name:     "Won",
		Accuracy: 0,
		Users:    []string{"KOR"},
	},
	{
		Alpha3:   "LAK",
		Numeric:  "418",
		Symbol:   "₭",
		Name:     "Lao Kip",
		Accuracy: 2,
		Users:    []string{"LAO"},
	},
	{
		Alpha3:   "NIO",
		Numeric:  "558",
		Symbol:   "C$",
		Name:     "Cordoba Oro",
		Accuracy: 2,
		Users:    []string{"NIC"},
	},
	{
		Alpha3:   "RUB",
		Numeric:  "643",
		Symbol:   "₽",
		Name:     "Russian Ruble",
		Accuracy: 2,
		Users:    []string{"RUS"},
	},
	{
		Alpha3:   "TTD",
		Numeric:  "780",
		Symbol:   "TT$",
		Name:     "Trinidad and Tobago Dollar",
		Accuracy: 2,
		Users:    []string{"TTO"},
	},
	{
		Alpha3:   "VUV",
		Numeric:  "548",
		Symbol:   "",
		Name:     "Vatu",
		Accuracy: 0,
		Users:    []string{"VUT"},
	},
	{
		Alpha3:   "XCD",
		Numeric:  "951",
		Symbol:   "$",
		Name:     "East Caribbean Dollar",
		Accuracy: 2,
		Users:    []string{"AIA", "DMA", "GRD", "LCA", "ATG", "VCT", "KNA", "MSR"},
	},
	{
		Alpha3:   "CNY",
		Numeric:  "156",
		Symbol:   "¥",
		Name:     "Yuan Renminbi",
		Accuracy: 2,
		Users:    []string{"CHN", "ZWE"},
	},
	{
		Alpha3:   "KMF",
		Numeric:  "174",
		Symbol:   "CF",
		Name:     "Comorian Franc",
		Accuracy: 0,
		Users:    []string{"COM"},
	},
	{
		Alpha3:   "HTG",
		Numeric:  "332",
		Symbol:   "G",
		Name:     "Gourde",
		Accuracy: 2,
		Users:    []string{"HTI"},
	},
	{
		Alpha3:   "TWD",
		Numeric:  "901",
		Symbol:   "NT$",
		Name:     "New Taiwan Dollar",
		Accuracy: 2,
		Users:    []string{"TWN"},
	},
	{
		Alpha3:   "CLP",
		Numeric:  "152",
		Symbol:   "$",
		Name:     "Chilean Peso",
		Accuracy: 0,
		Users:    []string{"CHL"},
	},
	{
		Alpha3:   "GHS",
		Numeric:  "936",
		Symbol:   "",
		Name:     "Ghana Cedi",
		Accuracy: 2,
		Users:    []string{"GHA"},
	},
	{
		Alpha3:   "LBP",
		Numeric:  "422",
		Symbol:   "£",
		Name:     "Lebanese Pound",
		Accuracy: 2,
		Users:    []string{"LBN"},
	},
	{
		Alpha3:   "TMT",
		Numeric:  "934",
		Symbol:   "",
		Name:     "Turkmenistan New Manat",
		Accuracy: 2,
		Users:    []string{"TKM"},
	},
	{
		Alpha3:   "UZS",
		Numeric:  "860",
		Symbol:   "лв",
		Name:     "Uzbekistan Sum",
		Accuracy: 2,
		Users:    []string{"UZB"},
	},
	{
		Alpha3:   "CHW",
		Numeric:  "948",
		Symbol:   "",
		Name:     "WIR Franc",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "SYP",
		Numeric:  "760",
		Symbol:   "£",
		Name:     "Syrian Pound",
		Accuracy: 2,
		Users:    []string{"SYR"},
	},
	{
		Alpha3:   "VND",
		Numeric:  "704",
		Symbol:   "₫",
		Name:     "Dong",
		Accuracy: 0,
		Users:    []string{"VNM"},
	},
	{
		Alpha3:   "DZD",
		Numeric:  "012",
		Symbol:   "",
		Name:     "Algerian Dinar",
		Accuracy: 2,
		Users:    []string{"ESH", "DZA"},
	},
	{
		Alpha3:   "BHD",
		Numeric:  "048",
		Symbol:   ".د.ب",
		Name:     "Bahraini Dinar",
		Accuracy: 3,
		Users:    []string{"BHR"},
	},
	{
		Alpha3:   "JPY",
		Numeric:  "392",
		Symbol:   "¥",
		Name:     "Yen",
		Accuracy: 0,
		Users:    []string{"ZWE", "JPN"},
	},
	{
		Alpha3:   "KES",
		Numeric:  "404",
		Symbol:   "KSh,",
		Name:     "Kenyan Shilling",
		Accuracy: 2,
		Users:    []string{"KEN"},
	},
	{
		Alpha3:   "PYG",
		Numeric:  "600",
		Symbol:   "Gs",
		Name:     "Guarani",
		Accuracy: 0,
		Users:    []string{"PRY"},
	},
	{
		Alpha3:   "CUC",
		Numeric:  "931",
		Symbol:   "$",
		Name:     "Peso Convertible",
		Accuracy: 2,
		Users:    []string{"CUB"},
	},
	{
		Alpha3:   "LSL",
		Numeric:  "426",
		Symbol:   "L",
		Name:     "Loti",
		Accuracy: 2,
		Users:    []string{"LSO"},
	},
	{
		Alpha3:   "MYR",
		Numeric:  "458",
		Symbol:   "RM",
		Name:     "Malaysian Ringgit",
		Accuracy: 2,
		Users:    []string{"MYS"},
	},
	{
		Alpha3:   "ZWL",
		Numeric:  "932",
		Symbol:   "",
		Name:     "Zimbabwe Dollar",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "SVC",
		Numeric:  "222",
		Symbol:   "",
		Name:     "El Salvador Colon",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "LKR",
		Numeric:  "144",
		Symbol:   "₨",
		Name:     "Sri Lanka Rupee",
		Accuracy: 2,
		Users:    []string{"LKA"},
	},
	{
		Alpha3:   "YER",
		Numeric:  "886",
		Symbol:   "﷼",
		Name:     "Yemeni Rial",
		Accuracy: 2,
		Users:    []string{"YEM"},
	},
	{
		Alpha3:   "AUD",
		Numeric:  "036",
		Symbol:   "$",
		Name:     "Australian Dollar",
		Accuracy: 2,
		Users:    []string{"CXR", "ATA", "HMD", "CCK", "NFK", "AUS", "KIR", "TUV", "NRU"},
	},
	{
		Alpha3:   "DJF",
		Numeric:  "262",
		Symbol:   "Fdj",
		Name:     "Djibouti Franc",
		Accuracy: 0,
		Users:    []string{"DJI"},
	},
	{
		Alpha3:   "RWF",
		Numeric:  "646",
		Symbol:   "FRw",
		Name:     "Rwanda Franc",
		Accuracy: 0,
		Users:    []string{"RWA"},
	},
	{
		Alpha3:   "TRY",
		Numeric:  "949",
		Symbol:   "₺",
		Name:     "Turkish Lira",
		Accuracy: 2,
		Users:    []string{"TUR"},
	},
	{
		Alpha3:   "XOF",
		Numeric:  "952",
		Symbol:   "CFA",
		Name:     "CFA Franc BCEAO",
		Accuracy: 0,
		Users:    []string{"NER", "BEN", "TGO", "CIV", "SEN", "MLI", "BFA", "GNB"},
	},
	{
		Alpha3:   "INR",
		Numeric:  "356",
		Symbol:   "₹",
		Name:     "Indian Rupee",
		Accuracy: 2,
		Users:    []string{"ZWE", "BTN", "IND"},
	},
	{
		Alpha3:   "MXV",
		Numeric:  "979",
		Symbol:   "",
		Name:     "Mexican Unidad de Inversion (UDI)",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "MDL",
		Numeric:  "498",
		Symbol:   "L",
		Name:     "Moldovan Leu",
		Accuracy: 2,
		Users:    []string{"MDA"},
	},
	{
		Alpha3:   "VES",
		Numeric:  "928",
		Symbol:   "",
		Name:     "Bolívar Soberano",
		Accuracy: 2,
		Users:    []string(nil),
	},
	{
		Alpha3:   "BZD",
		Numeric:  "084",
		Symbol:   "BZ$",
		Name:     "Belize Dollar",
		Accuracy: 2,
		Users:    []string{"BLZ"},
	},
	{
		Alpha3:   "COP",
		Numeric:  "170",
		Symbol:   "$",
		Name:     "Colombian Peso",
		Accuracy: 2,
		Users:    []string{"COL"},
	},
	{
		Alpha3:   "HNL",
		Numeric:  "340",
		Symbol:   "L",
		Name:     "Lempira",
		Accuracy: 2,
		Users:    []string{"HND"},
	},
	{
		Alpha3:   "KWD",
		Numeric:  "414",
		Symbol:   "د.ك",
		Name:     "Kuwaiti Dinar",
		Accuracy: 3,
		Users:    []string{"KWT"},
	},
	{
		Alpha3:   "MUR",
		Numeric:  "480",
		Symbol:   "₨",
		Name:     "Mauritius Rupee",
		Accuracy: 2,
		Users:    []string{"MUS"},
	},
	{
		Alpha3:   "PEN",
		Numeric:  "604",
		Symbol:   "S/.",
		Name:     "Sol",
		Accuracy: 2,
		Users:    []string{"PER"},
	},
	{
		Alpha3:   "ALL",
		Numeric:  "008",
		Symbol:   "Lek",
		Name:     "Lek",
		Accuracy: 2,
		Users:    []string{"ALB"},
	},
	{
		Alpha3:   "AMD",
		Numeric:  "051",
		Symbol:   "դր.",
		Name:     "Armenian Dram",
		Accuracy: 2,
		Users:    []string{"ARM"},
	},
	{
		Alpha3:   "EGP",
		Numeric:  "818",
		Symbol:   "£",
		Name:     "Egyptian Pound",
		Accuracy: 2,
		Users:    []string{"EGY"},
	},
	{
		Alpha3:   "SZL",
		Numeric:  "748",
		Symbol:   "E",
		Name:     "Lilangeni",
		Accuracy: 2,
		Users:    []string{"SWZ"},
	},
	{
		Alpha3:   "ZAR",
		Numeric:  "710",
		Symbol:   "R",
		Name:     "Rand",
		Accuracy: 2,
		Users:    []string{"ZWE", "NAM", "LSO", "ZAF"},
	},
}
