package currency

// Updated at: 2021-01-21 17:44:37.926314134 +0300 MSK m=+1.622478497
var List = []Currency{
	{
		Alpha3:   "DKK",
		Numeric:  "208",
		Symbol:   "kr.",
		Name:     "Danish Krone",
		Accuracy: 2,
		Users:    []string{"GRL", "DNK", "FRO"},
		AltNames: []string(nil),
		Tags:     []string{"danish"},
	},
	{
		Alpha3:   "DOP",
		Numeric:  "214",
		Symbol:   "RD$",
		Name:     "Dominican Peso",
		Accuracy: 2,
		Users:    []string{"DOM"},
		AltNames: []string(nil),
		Tags:     []string{"dominican"},
	},
	{
		Alpha3:   "ISK",
		Numeric:  "352",
		Symbol:   "kr",
		Name:     "Iceland Krona",
		Accuracy: 0,
		Users:    []string{"ISL"},
		AltNames: []string(nil),
		Tags:     []string{"iceland"},
	},
	{
		Alpha3:   "LYD",
		Numeric:  "434",
		Symbol:   "ل.د",
		Name:     "Libyan Dinar",
		Accuracy: 3,
		Users:    []string{"LBY"},
		AltNames: []string(nil),
		Tags:     []string{"libyan"},
	},
	{
		Alpha3:   "MNT",
		Numeric:  "496",
		Symbol:   "₮",
		Name:     "Tugrik",
		Accuracy: 2,
		Users:    []string{"MNG"},
		AltNames: []string(nil),
		Tags:     []string{"tugrik"},
	},
	{
		Alpha3:   "MAD",
		Numeric:  "504",
		Symbol:   "DH",
		Name:     "Moroccan Dirham",
		Accuracy: 2,
		Users:    []string{"ESH", "MAR"},
		AltNames: []string(nil),
		Tags:     []string{"moroccan"},
	},
	{
		Alpha3:   "PKR",
		Numeric:  "586",
		Symbol:   "₨",
		Name:     "Pakistan Rupee",
		Accuracy: 2,
		Users:    []string{"PAK"},
		AltNames: []string(nil),
		Tags:     []string{"pakistan"},
	},
	{
		Alpha3:   "BZD",
		Numeric:  "084",
		Symbol:   "BZ$",
		Name:     "Belize Dollar",
		Accuracy: 2,
		Users:    []string{"BLZ"},
		AltNames: []string(nil),
		Tags:     []string{"belize"},
	},
	{
		Alpha3:   "ETB",
		Numeric:  "230",
		Symbol:   "ብር",
		Name:     "Ethiopian Birr",
		Accuracy: 2,
		Users:    []string{"ETH"},
		AltNames: []string(nil),
		Tags:     []string{"birr", "ethiopian"},
	},
	{
		Alpha3:   "CHW",
		Numeric:  "948",
		Symbol:   "",
		Name:     "WIR Franc",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "YER",
		Numeric:  "886",
		Symbol:   "﷼",
		Name:     "Yemeni Rial",
		Accuracy: 2,
		Users:    []string{"YEM"},
		AltNames: []string(nil),
		Tags:     []string{"yemeni"},
	},
	{
		Alpha3:   "VUV",
		Numeric:  "548",
		Symbol:   "",
		Name:     "Vatu",
		Accuracy: 0,
		Users:    []string{"VUT"},
		AltNames: []string(nil),
		Tags:     []string{"vatu"},
	},
	{
		Alpha3:   "CAD",
		Numeric:  "124",
		Symbol:   "$",
		Name:     "Canadian Dollar",
		Accuracy: 2,
		Users:    []string{"CAN"},
		AltNames: []string(nil),
		Tags:     []string{"canadian"},
	},
	{
		Alpha3:   "SVC",
		Numeric:  "222",
		Symbol:   "",
		Name:     "El Salvador Colon",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"el", "salvador"},
	},
	{
		Alpha3:   "HTG",
		Numeric:  "332",
		Symbol:   "G",
		Name:     "Gourde",
		Accuracy: 2,
		Users:    []string{"HTI"},
		AltNames: []string(nil),
		Tags:     []string{"gourde"},
	},
	{
		Alpha3:   "LBP",
		Numeric:  "422",
		Symbol:   "£",
		Name:     "Lebanese Pound",
		Accuracy: 2,
		Users:    []string{"LBN"},
		AltNames: []string(nil),
		Tags:     []string{"lebanese"},
	},
	{
		Alpha3:   "MKD",
		Numeric:  "807",
		Symbol:   "ден",
		Name:     "Denar",
		Accuracy: 2,
		Users:    []string{"MKD"},
		AltNames: []string(nil),
		Tags:     []string{"denar"},
	},
	{
		Alpha3:   "SAR",
		Numeric:  "682",
		Symbol:   "﷼",
		Name:     "Saudi Riyal",
		Accuracy: 2,
		Users:    []string{"SAU"},
		AltNames: []string(nil),
		Tags:     []string{"saudi", "riyal"},
	},
	{
		Alpha3:   "TND",
		Numeric:  "788",
		Symbol:   "د.ت",
		Name:     "Tunisian Dinar",
		Accuracy: 3,
		Users:    []string{"TUN"},
		AltNames: []string(nil),
		Tags:     []string{"tunisian"},
	},
	{
		Alpha3:   "DJF",
		Numeric:  "262",
		Symbol:   "Fdj",
		Name:     "Djibouti Franc",
		Accuracy: 0,
		Users:    []string{"DJI"},
		AltNames: []string(nil),
		Tags:     []string{"djibouti"},
	},
	{
		Alpha3:   "GMD",
		Numeric:  "270",
		Symbol:   "D",
		Name:     "Dalasi",
		Accuracy: 2,
		Users:    []string{"GMB"},
		AltNames: []string(nil),
		Tags:     []string{"dalasi"},
	},
	{
		Alpha3:   "HUF",
		Numeric:  "348",
		Symbol:   "Ft",
		Name:     "Forint",
		Accuracy: 2,
		Users:    []string{"HUN"},
		AltNames: []string(nil),
		Tags:     []string{"forint"},
	},
	{
		Alpha3:   "RSD",
		Numeric:  "941",
		Symbol:   "Дин.",
		Name:     "Serbian Dinar",
		Accuracy: 2,
		Users:    []string{"SRB"},
		AltNames: []string(nil),
		Tags:     []string{"serbian"},
	},
	{
		Alpha3:   "TRY",
		Numeric:  "949",
		Symbol:   "₺",
		Name:     "Turkish Lira",
		Accuracy: 2,
		Users:    []string{"TUR"},
		AltNames: []string(nil),
		Tags:     []string{"lira", "turkish"},
	},
	{
		Alpha3:   "SSP",
		Numeric:  "728",
		Symbol:   "£",
		Name:     "South Sudanese Pound",
		Accuracy: 2,
		Users:    []string{"SSD"},
		AltNames: []string(nil),
		Tags:     []string{"south"},
	},
	{
		Alpha3:   "BIF",
		Numeric:  "108",
		Symbol:   "FBu",
		Name:     "Burundi Franc",
		Accuracy: 0,
		Users:    []string{"BDI"},
		AltNames: []string(nil),
		Tags:     []string{"burundi"},
	},
	{
		Alpha3:   "COP",
		Numeric:  "170",
		Symbol:   "$",
		Name:     "Colombian Peso",
		Accuracy: 2,
		Users:    []string{"COL"},
		AltNames: []string(nil),
		Tags:     []string{"colombian"},
	},
	{
		Alpha3:   "CRC",
		Numeric:  "188",
		Symbol:   "₡",
		Name:     "Costa Rican Colon",
		Accuracy: 2,
		Users:    []string{"CRI"},
		AltNames: []string(nil),
		Tags:     []string{"costa", "rican"},
	},
	{
		Alpha3:   "ERN",
		Numeric:  "232",
		Symbol:   "ናቕፋ",
		Name:     "Nakfa",
		Accuracy: 2,
		Users:    []string{"ERI"},
		AltNames: []string(nil),
		Tags:     []string{"nakfa"},
	},
	{
		Alpha3:   "GYD",
		Numeric:  "328",
		Symbol:   "$",
		Name:     "Guyana Dollar",
		Accuracy: 2,
		Users:    []string{"GUY"},
		AltNames: []string(nil),
		Tags:     []string{"guyana"},
	},
	{
		Alpha3:   "JOD",
		Numeric:  "400",
		Symbol:   "د.ا",
		Name:     "Jordanian Dinar",
		Accuracy: 3,
		Users:    []string{"JOR"},
		AltNames: []string(nil),
		Tags:     []string{"jordanian"},
	},
	{
		Alpha3:   "NGN",
		Numeric:  "566",
		Symbol:   "₦",
		Name:     "Naira",
		Accuracy: 2,
		Users:    []string{"NGA"},
		AltNames: []string(nil),
		Tags:     []string{"naira"},
	},
	{
		Alpha3:   "XAF",
		Numeric:  "950",
		Symbol:   "FCFA",
		Name:     "CFA Franc BEAC",
		Accuracy: 0,
		Users:    []string{"CAF", "TCD", "GNQ", "COG", "CMR", "GAB"},
		AltNames: []string(nil),
		Tags:     []string{"beac"},
	},
	{
		Alpha3:   "KMF",
		Numeric:  "174",
		Symbol:   "CF",
		Name:     "Comorian Franc",
		Accuracy: 0,
		Users:    []string{"COM"},
		AltNames: []string(nil),
		Tags:     []string{"comorian"},
	},
	{
		Alpha3:   "NZD",
		Numeric:  "554",
		Symbol:   "$",
		Name:     "New Zealand Dollar",
		Accuracy: 2,
		Users:    []string{"COK", "NIU", "PCN", "NZL", "TKL"},
		AltNames: []string(nil),
		Tags:     []string{"zealand"},
	},
	{
		Alpha3:   "CZK",
		Numeric:  "203",
		Symbol:   "Kč",
		Name:     "Czech Koruna",
		Accuracy: 2,
		Users:    []string{"CZE"},
		AltNames: []string(nil),
		Tags:     []string{"czech", "koruna"},
	},
	{
		Alpha3:   "MWK",
		Numeric:  "454",
		Symbol:   "MK",
		Name:     "Malawi Kwacha",
		Accuracy: 2,
		Users:    []string{"MWI"},
		AltNames: []string(nil),
		Tags:     []string{"malawi"},
	},
	{
		Alpha3:   "BMD",
		Numeric:  "060",
		Symbol:   "",
		Name:     "Bermudian Dollar",
		Accuracy: 2,
		Users:    []string{"BMU"},
		AltNames: []string(nil),
		Tags:     []string{"bermudian"},
	},
	{
		Alpha3:   "CNY",
		Numeric:  "156",
		Symbol:   "¥",
		Name:     "Yuan Renminbi",
		Accuracy: 2,
		Users:    []string{"ZWE", "CHN"},
		AltNames: []string(nil),
		Tags:     []string{"renminbi", "yuan"},
	},
	{
		Alpha3:   "CUP",
		Numeric:  "192",
		Symbol:   "",
		Name:     "Cuban Peso",
		Accuracy: 2,
		Users:    []string{"CUB"},
		AltNames: []string(nil),
		Tags:     []string{"cuban"},
	},
	{
		Alpha3:   "LSL",
		Numeric:  "426",
		Symbol:   "L",
		Name:     "Loti",
		Accuracy: 2,
		Users:    []string{"LSO"},
		AltNames: []string(nil),
		Tags:     []string{"loti"},
	},
	{
		Alpha3:   "CHE",
		Numeric:  "947",
		Symbol:   "",
		Name:     "WIR Euro",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "SYP",
		Numeric:  "760",
		Symbol:   "£",
		Name:     "Syrian Pound",
		Accuracy: 2,
		Users:    []string{"SYR"},
		AltNames: []string(nil),
		Tags:     []string{"syrian"},
	},
	{
		Alpha3:   "OMR",
		Numeric:  "512",
		Symbol:   "﷼",
		Name:     "Rial Omani",
		Accuracy: 3,
		Users:    []string{"OMN"},
		AltNames: []string(nil),
		Tags:     []string{"omani"},
	},
	{
		Alpha3:   "ARS",
		Numeric:  "032",
		Symbol:   "$",
		Name:     "Argentine Peso",
		Accuracy: 2,
		Users:    []string{"ARG"},
		AltNames: []string(nil),
		Tags:     []string{"argentine"},
	},
	{
		Alpha3:   "AUD",
		Numeric:  "036",
		Symbol:   "$",
		Name:     "Australian Dollar",
		Accuracy: 2,
		Users:    []string{"ATA", "TUV", "CCK", "NRU", "CXR", "HMD", "KIR", "AUS", "NFK"},
		AltNames: []string(nil),
		Tags:     []string{"australian"},
	},
	{
		Alpha3:   "COU",
		Numeric:  "970",
		Symbol:   "",
		Name:     "Unidad de Valor Real",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"valor"},
	},
	{
		Alpha3:   "JMD",
		Numeric:  "388",
		Symbol:   "J$",
		Name:     "Jamaican Dollar",
		Accuracy: 2,
		Users:    []string{"JAM"},
		AltNames: []string(nil),
		Tags:     []string{"jamaican"},
	},
	{
		Alpha3:   "CHF",
		Numeric:  "756",
		Symbol:   "CHF",
		Name:     "Swiss Franc",
		Accuracy: 2,
		Users:    []string{"LIE", "CHE"},
		AltNames: []string(nil),
		Tags:     []string{"swiss"},
	},
	{
		Alpha3:   "MYR",
		Numeric:  "458",
		Symbol:   "RM",
		Name:     "Malaysian Ringgit",
		Accuracy: 2,
		Users:    []string{"MYS"},
		AltNames: []string(nil),
		Tags:     []string{"malaysian", "ringgit"},
	},
	{
		Alpha3:   "MMK",
		Numeric:  "104",
		Symbol:   "K",
		Name:     "Kyat",
		Accuracy: 2,
		Users:    []string{"MMR"},
		AltNames: []string(nil),
		Tags:     []string{"kyat"},
	},
	{
		Alpha3:   "PAB",
		Numeric:  "590",
		Symbol:   "B/.",
		Name:     "Balboa",
		Accuracy: 2,
		Users:    []string{"PAN"},
		AltNames: []string(nil),
		Tags:     []string{"balboa"},
	},
	{
		Alpha3:   "QAR",
		Numeric:  "634",
		Symbol:   "﷼",
		Name:     "Qatari Rial",
		Accuracy: 2,
		Users:    []string{"QAT"},
		AltNames: []string(nil),
		Tags:     []string{"qatari"},
	},
	{
		Alpha3:   "USN",
		Numeric:  "997",
		Symbol:   "",
		Name:     "US Dollar (Next day)",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"next", "day"},
	},
	{
		Alpha3:   "CUC",
		Numeric:  "931",
		Symbol:   "$",
		Name:     "Peso Convertible",
		Accuracy: 2,
		Users:    []string{"CUB"},
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "HNL",
		Numeric:  "340",
		Symbol:   "L",
		Name:     "Lempira",
		Accuracy: 2,
		Users:    []string{"HND"},
		AltNames: []string(nil),
		Tags:     []string{"lempira"},
	},
	{
		Alpha3:   "HKD",
		Numeric:  "344",
		Symbol:   "",
		Name:     "Hong Kong Dollar",
		Accuracy: 2,
		Users:    []string{"HKG"},
		AltNames: []string(nil),
		Tags:     []string{"hong", "kong"},
	},
	{
		Alpha3:   "IDR",
		Numeric:  "360",
		Symbol:   "Rp",
		Name:     "Rupiah",
		Accuracy: 2,
		Users:    []string{"IDN"},
		AltNames: []string(nil),
		Tags:     []string{"rupiah"},
	},
	{
		Alpha3:   "KPW",
		Numeric:  "408",
		Symbol:   "₩",
		Name:     "North Korean Won",
		Accuracy: 2,
		Users:    []string{"PRK"},
		AltNames: []string(nil),
		Tags:     []string{"korean", "north"},
	},
	{
		Alpha3:   "TZS",
		Numeric:  "834",
		Symbol:   "TSh",
		Name:     "Tanzanian Shilling",
		Accuracy: 2,
		Users:    []string{"TZA"},
		AltNames: []string(nil),
		Tags:     []string{"tanzanian"},
	},
	{
		Alpha3:   "UAH",
		Numeric:  "980",
		Symbol:   "₴",
		Name:     "Hryvnia",
		Accuracy: 2,
		Users:    []string{"UKR"},
		AltNames: []string(nil),
		Tags:     []string{"hryvnia"},
	},
	{
		Alpha3:   "INR",
		Numeric:  "356",
		Symbol:   "₹",
		Name:     "Indian Rupee",
		Accuracy: 2,
		Users:    []string{"ZWE", "IND", "BTN"},
		AltNames: []string(nil),
		Tags:     []string{"indian"},
	},
	{
		Alpha3:   "BTN",
		Numeric:  "064",
		Symbol:   "Nu.",
		Name:     "Ngultrum",
		Accuracy: 2,
		Users:    []string{"BTN"},
		AltNames: []string(nil),
		Tags:     []string{"ngultrum"},
	},
	{
		Alpha3:   "NOK",
		Numeric:  "578",
		Symbol:   "kr",
		Name:     "Norwegian Krone",
		Accuracy: 2,
		Users:    []string{"BVT", "NOR", "SJM"},
		AltNames: []string(nil),
		Tags:     []string{"norwegian"},
	},
	{
		Alpha3:   "GNF",
		Numeric:  "324",
		Symbol:   "FG",
		Name:     "Guinean Franc",
		Accuracy: 0,
		Users:    []string{"GIN"},
		AltNames: []string(nil),
		Tags:     []string{"guinean"},
	},
	{
		Alpha3:   "KGS",
		Numeric:  "417",
		Symbol:   "лв",
		Name:     "Som",
		Accuracy: 2,
		Users:    []string{"KGZ"},
		AltNames: []string(nil),
		Tags:     []string{"som"},
	},
	{
		Alpha3:   "PHP",
		Numeric:  "608",
		Symbol:   "₱",
		Name:     "Philippine Peso",
		Accuracy: 2,
		Users:    []string{"PHL"},
		AltNames: []string(nil),
		Tags:     []string{"philippine"},
	},
	{
		Alpha3:   "TJS",
		Numeric:  "972",
		Symbol:   "ЅM",
		Name:     "Somoni",
		Accuracy: 2,
		Users:    []string{"TJK"},
		AltNames: []string(nil),
		Tags:     []string{"somoni"},
	},
	{
		Alpha3:   "ZWL",
		Numeric:  "932",
		Symbol:   "",
		Name:     "Zimbabwe Dollar",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"zimbabwe"},
	},
	{
		Alpha3:   "EUR",
		Numeric:  "978",
		Symbol:   "€",
		Name:     "Euro",
		Accuracy: 2,
		Users:    []string{"ITA", "KOS", "ZWE", "ALA", "MTQ", "BEL", "SVK", "NLD", "EST", "SVN", "CYP", "MNE", "LTU", "FIN", "MCO", "MAF", "LVA", "AND", "IRL", "ATF", "MYT", "GRC", "LUX", "FRA", "BLM", "SPM", "GUF", "AUT", "DEU", "GLP", "MLT", "PRT", "REU", "VAT", "ESP", "SMR"},
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "EGP",
		Numeric:  "818",
		Symbol:   "£",
		Name:     "Egyptian Pound",
		Accuracy: 2,
		Users:    []string{"EGY"},
		AltNames: []string(nil),
		Tags:     []string{"egyptian"},
	},
	{
		Alpha3:   "LAK",
		Numeric:  "418",
		Symbol:   "₭",
		Name:     "Lao Kip",
		Accuracy: 2,
		Users:    []string{"LAO"},
		AltNames: []string(nil),
		Tags:     []string{"lao", "kip"},
	},
	{
		Alpha3:   "MGA",
		Numeric:  "969",
		Symbol:   "Ar",
		Name:     "Malagasy Ariary",
		Accuracy: 2,
		Users:    []string{"MDG"},
		AltNames: []string(nil),
		Tags:     []string{"ariary", "malagasy"},
	},
	{
		Alpha3:   "MZN",
		Numeric:  "943",
		Symbol:   "MT",
		Name:     "Mozambique Metical",
		Accuracy: 2,
		Users:    []string{"MOZ"},
		AltNames: []string(nil),
		Tags:     []string{"mozambique", "metical"},
	},
	{
		Alpha3:   "NAD",
		Numeric:  "516",
		Symbol:   "$",
		Name:     "Namibia Dollar",
		Accuracy: 2,
		Users:    []string{"NAM"},
		AltNames: []string(nil),
		Tags:     []string{"namibia"},
	},
	{
		Alpha3:   "SGD",
		Numeric:  "702",
		Symbol:   "$",
		Name:     "Singapore Dollar",
		Accuracy: 2,
		Users:    []string{"BRN", "SGP"},
		AltNames: []string(nil),
		Tags:     []string{"singapore"},
	},
	{
		Alpha3:   "AZN",
		Numeric:  "944",
		Symbol:   "₼",
		Name:     "Azerbaijan Manat",
		Accuracy: 2,
		Users:    []string{"AZE"},
		AltNames: []string(nil),
		Tags:     []string{"azerbaijan"},
	},
	{
		Alpha3:   "BBD",
		Numeric:  "052",
		Symbol:   "$",
		Name:     "Barbados Dollar",
		Accuracy: 2,
		Users:    []string{"BRB"},
		AltNames: []string(nil),
		Tags:     []string{"barbados"},
	},
	{
		Alpha3:   "FKP",
		Numeric:  "238",
		Symbol:   "",
		Name:     "Falkland Islands Pound",
		Accuracy: 2,
		Users:    []string{"FLK"},
		AltNames: []string(nil),
		Tags:     []string{"falkland"},
	},
	{
		Alpha3:   "MDL",
		Numeric:  "498",
		Symbol:   "L",
		Name:     "Moldovan Leu",
		Accuracy: 2,
		Users:    []string{"MDA"},
		AltNames: []string(nil),
		Tags:     []string{"moldovan"},
	},
	{
		Alpha3:   "UGX",
		Numeric:  "800",
		Symbol:   "USh",
		Name:     "Uganda Shilling",
		Accuracy: 0,
		Users:    []string{"UGA"},
		AltNames: []string(nil),
		Tags:     []string{"uganda"},
	},
	{
		Alpha3:   "SOS",
		Numeric:  "706",
		Symbol:   "S",
		Name:     "Somali Shilling",
		Accuracy: 2,
		Users:    []string{"SOM"},
		AltNames: []string(nil),
		Tags:     []string{"somali"},
	},
	{
		Alpha3:   "XCD",
		Numeric:  "951",
		Symbol:   "$",
		Name:     "East Caribbean Dollar",
		Accuracy: 2,
		Users:    []string{"GRD", "VCT", "KNA", "AIA", "ATG", "MSR", "DMA", "LCA"},
		AltNames: []string(nil),
		Tags:     []string{"east", "caribbean"},
	},
	{
		Alpha3:   "AMD",
		Numeric:  "051",
		Symbol:   "դր.",
		Name:     "Armenian Dram",
		Accuracy: 2,
		Users:    []string{"ARM"},
		AltNames: []string(nil),
		Tags:     []string{"dram", "armenian"},
	},
	{
		Alpha3:   "BDT",
		Numeric:  "050",
		Symbol:   "৳",
		Name:     "Taka",
		Accuracy: 2,
		Users:    []string{"BGD"},
		AltNames: []string(nil),
		Tags:     []string{"taka"},
	},
	{
		Alpha3:   "ILS",
		Numeric:  "376",
		Symbol:   "₪",
		Name:     "New Israeli Sheqel",
		Accuracy: 2,
		Users:    []string{"ISR", "PSE"},
		AltNames: []string(nil),
		Tags:     []string{"israeli", "sheqel"},
	},
	{
		Alpha3:   "JPY",
		Numeric:  "392",
		Symbol:   "¥",
		Name:     "Yen",
		Accuracy: 0,
		Users:    []string{"ZWE", "JPN"},
		AltNames: []string(nil),
		Tags:     []string{"yen"},
	},
	{
		Alpha3:   "MXN",
		Numeric:  "484",
		Symbol:   "$",
		Name:     "Mexican Peso",
		Accuracy: 2,
		Users:    []string{"MEX"},
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "PLN",
		Numeric:  "985",
		Symbol:   "zł",
		Name:     "Zloty",
		Accuracy: 2,
		Users:    []string{"POL"},
		AltNames: []string(nil),
		Tags:     []string{"zloty"},
	},
	{
		Alpha3:   "GBP",
		Numeric:  "826",
		Symbol:   "£",
		Name:     "Pound Sterling",
		Accuracy: 2,
		Users:    []string{"ZWE", "SGS", "ATA", "GBR", "IMN", "JEY", "GGY"},
		AltNames: []string(nil),
		Tags:     []string{"sterling"},
	},
	{
		Alpha3:   "LRD",
		Numeric:  "430",
		Symbol:   "$",
		Name:     "Liberian Dollar",
		Accuracy: 2,
		Users:    []string{"LBR"},
		AltNames: []string(nil),
		Tags:     []string{"liberian"},
	},
	{
		Alpha3:   "MOP",
		Numeric:  "446",
		Symbol:   "",
		Name:     "Pataca",
		Accuracy: 2,
		Users:    []string{"MAC"},
		AltNames: []string(nil),
		Tags:     []string{"pataca"},
	},
	{
		Alpha3:   "MVR",
		Numeric:  "462",
		Symbol:   "Rf",
		Name:     "Rufiyaa",
		Accuracy: 2,
		Users:    []string{"MDV"},
		AltNames: []string(nil),
		Tags:     []string{"rufiyaa"},
	},
	{
		Alpha3:   "TTD",
		Numeric:  "780",
		Symbol:   "TT$",
		Name:     "Trinidad and Tobago Dollar",
		Accuracy: 2,
		Users:    []string{"TTO"},
		AltNames: []string(nil),
		Tags:     []string{"trinidad", "and", "tobago"},
	},
	{
		Alpha3:   "AWG",
		Numeric:  "533",
		Symbol:   "",
		Name:     "Aruban Florin",
		Accuracy: 2,
		Users:    []string{"ABW"},
		AltNames: []string(nil),
		Tags:     []string{"florin", "aruban"},
	},
	{
		Alpha3:   "BRL",
		Numeric:  "986",
		Symbol:   "R$",
		Name:     "Brazilian Real",
		Accuracy: 2,
		Users:    []string{"BRA"},
		AltNames: []string(nil),
		Tags:     []string{"brazilian"},
	},
	{
		Alpha3:   "WST",
		Numeric:  "882",
		Symbol:   "WS$",
		Name:     "Tala",
		Accuracy: 2,
		Users:    []string{"WSM"},
		AltNames: []string(nil),
		Tags:     []string{"tala"},
	},
	{
		Alpha3:   "SEK",
		Numeric:  "752",
		Symbol:   "kr",
		Name:     "Swedish Krona",
		Accuracy: 2,
		Users:    []string{"SWE"},
		AltNames: []string(nil),
		Tags:     []string{"swedish"},
	},
	{
		Alpha3:   "CLF",
		Numeric:  "990",
		Symbol:   "",
		Name:     "Unidad de Fomento",
		Accuracy: 4,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"fomento"},
	},
	{
		Alpha3:   "KZT",
		Numeric:  "398",
		Symbol:   "лв",
		Name:     "Tenge",
		Accuracy: 2,
		Users:    []string{"KAZ"},
		AltNames: []string(nil),
		Tags:     []string{"tenge"},
	},
	{
		Alpha3:   "PYG",
		Numeric:  "600",
		Symbol:   "Gs",
		Name:     "Guarani",
		Accuracy: 0,
		Users:    []string{"PRY"},
		AltNames: []string(nil),
		Tags:     []string{"guarani"},
	},
	{
		Alpha3:   "SRD",
		Numeric:  "968",
		Symbol:   "$",
		Name:     "Surinam Dollar",
		Accuracy: 2,
		Users:    []string{"SUR"},
		AltNames: []string(nil),
		Tags:     []string{"surinam"},
	},
	{
		Alpha3:   "AFN",
		Numeric:  "971",
		Symbol:   "؋",
		Name:     "Afghani",
		Accuracy: 2,
		Users:    []string{"AFG"},
		AltNames: []string(nil),
		Tags:     []string{"afghani"},
	},
	{
		Alpha3:   "LKR",
		Numeric:  "144",
		Symbol:   "₨",
		Name:     "Sri Lanka Rupee",
		Accuracy: 2,
		Users:    []string{"LKA"},
		AltNames: []string(nil),
		Tags:     []string{"sri", "lanka"},
	},
	{
		Alpha3:   "SDG",
		Numeric:  "938",
		Symbol:   "SD",
		Name:     "Sudanese Pound",
		Accuracy: 2,
		Users:    []string{"SDN"},
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "DZD",
		Numeric:  "012",
		Symbol:   "",
		Name:     "Algerian Dinar",
		Accuracy: 2,
		Users:    []string{"ESH", "DZA"},
		AltNames: []string(nil),
		Tags:     []string{"algerian"},
	},
	{
		Alpha3:   "BND",
		Numeric:  "096",
		Symbol:   "$",
		Name:     "Brunei Dollar",
		Accuracy: 2,
		Users:    []string{"BRN", "SGP"},
		AltNames: []string(nil),
		Tags:     []string{"brunei"},
	},
	{
		Alpha3:   "FJD",
		Numeric:  "242",
		Symbol:   "$",
		Name:     "Fiji Dollar",
		Accuracy: 2,
		Users:    []string{"FJI"},
		AltNames: []string(nil),
		Tags:     []string{"fiji"},
	},
	{
		Alpha3:   "MRU",
		Numeric:  "929",
		Symbol:   "",
		Name:     "Ouguiya",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"ouguiya"},
	},
	{
		Alpha3:   "SHP",
		Numeric:  "654",
		Symbol:   "",
		Name:     "Saint Helena Pound",
		Accuracy: 2,
		Users:    []string{"SHN"},
		AltNames: []string(nil),
		Tags:     []string{"helena", "saint"},
	},
	{
		Alpha3:   "UYW",
		Numeric:  "927",
		Symbol:   "",
		Name:     "Unidad Previsional",
		Accuracy: 4,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"previsional"},
	},
	{
		Alpha3:   "VND",
		Numeric:  "704",
		Symbol:   "₫",
		Name:     "Dong",
		Accuracy: 0,
		Users:    []string{"VNM"},
		AltNames: []string(nil),
		Tags:     []string{"dong"},
	},
	{
		Alpha3:   "UZS",
		Numeric:  "860",
		Symbol:   "лв",
		Name:     "Uzbekistan Sum",
		Accuracy: 2,
		Users:    []string{"UZB"},
		AltNames: []string(nil),
		Tags:     []string{"uzbekistan", "sum"},
	},
	{
		Alpha3:   "KHR",
		Numeric:  "116",
		Symbol:   "៛",
		Name:     "Riel",
		Accuracy: 2,
		Users:    []string{"KHM"},
		AltNames: []string(nil),
		Tags:     []string{"riel"},
	},
	{
		Alpha3:   "CLP",
		Numeric:  "152",
		Symbol:   "$",
		Name:     "Chilean Peso",
		Accuracy: 0,
		Users:    []string{"CHL"},
		AltNames: []string(nil),
		Tags:     []string{"chilean"},
	},
	{
		Alpha3:   "ANG",
		Numeric:  "532",
		Symbol:   "",
		Name:     "Netherlands Antillean Guilder",
		Accuracy: 2,
		Users:    []string{"SXM", "CUW"},
		AltNames: []string(nil),
		Tags:     []string{"antillean", "guilder", "netherlands"},
	},
	{
		Alpha3:   "GEL",
		Numeric:  "981",
		Symbol:   "ლ",
		Name:     "Lari",
		Accuracy: 2,
		Users:    []string{"GEO"},
		AltNames: []string(nil),
		Tags:     []string{"lari"},
	},
	{
		Alpha3:   "GIP",
		Numeric:  "292",
		Symbol:   "",
		Name:     "Gibraltar Pound",
		Accuracy: 2,
		Users:    []string{"GIB"},
		AltNames: []string(nil),
		Tags:     []string{"gibraltar"},
	},
	{
		Alpha3:   "GTQ",
		Numeric:  "320",
		Symbol:   "Q",
		Name:     "Quetzal",
		Accuracy: 2,
		Users:    []string{"GTM"},
		AltNames: []string(nil),
		Tags:     []string{"quetzal"},
	},
	{
		Alpha3:   "IRR",
		Numeric:  "364",
		Symbol:   "﷼",
		Name:     "Iranian Rial",
		Accuracy: 2,
		Users:    []string{"IRN"},
		AltNames: []string(nil),
		Tags:     []string{"iranian"},
	},
	{
		Alpha3:   "BSD",
		Numeric:  "044",
		Symbol:   "$",
		Name:     "Bahamian Dollar",
		Accuracy: 2,
		Users:    []string{"BHS"},
		AltNames: []string(nil),
		Tags:     []string{"bahamian"},
	},
	{
		Alpha3:   "STN",
		Numeric:  "930",
		Symbol:   "",
		Name:     "Dobra",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"dobra"},
	},
	{
		Alpha3:   "SCR",
		Numeric:  "690",
		Symbol:   "₨",
		Name:     "Seychelles Rupee",
		Accuracy: 2,
		Users:    []string{"SYC"},
		AltNames: []string(nil),
		Tags:     []string{"seychelles"},
	},
	{
		Alpha3:   "VES",
		Numeric:  "928",
		Symbol:   "",
		Name:     "Bolívar Soberano",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"bolívar", "soberano"},
	},
	{
		Alpha3:   "XOF",
		Numeric:  "952",
		Symbol:   "CFA",
		Name:     "CFA Franc BCEAO",
		Accuracy: 0,
		Users:    []string{"NER", "MLI", "CIV", "TGO", "BFA", "BEN", "SEN", "GNB"},
		AltNames: []string(nil),
		Tags:     []string{"bceao"},
	},
	{
		Alpha3:   "BOV",
		Numeric:  "984",
		Symbol:   "",
		Name:     "Mvdol",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"mvdol"},
	},
	{
		Alpha3:   "KYD",
		Numeric:  "136",
		Symbol:   "",
		Name:     "Cayman Islands Dollar",
		Accuracy: 2,
		Users:    []string{"CYM"},
		AltNames: []string(nil),
		Tags:     []string{"cayman"},
	},
	{
		Alpha3:   "BWP",
		Numeric:  "072",
		Symbol:   "P",
		Name:     "Pula",
		Accuracy: 2,
		Users:    []string{"ZWE", "BWA"},
		AltNames: []string(nil),
		Tags:     []string{"pula"},
	},
	{
		Alpha3:   "USD",
		Numeric:  "840",
		Symbol:   "$",
		Name:     "US Dollar",
		Accuracy: 2,
		Users:    []string{"VIR", "ZWE", "MHL", "PAN", "VGB", "BES", "SLV", "FSM", "ECU", "MNP", "USA", "GUM", "PRI", "PLW", "ASM", "TCA", "IOT", "TLS", "KHM"},
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "PGK",
		Numeric:  "598",
		Symbol:   "K",
		Name:     "Kina",
		Accuracy: 2,
		Users:    []string{"PNG"},
		AltNames: []string(nil),
		Tags:     []string{"kina"},
	},
	{
		Alpha3:   "RUB",
		Numeric:  "643",
		Symbol:   "₽",
		Name:     "Russian Ruble",
		Accuracy: 2,
		Users:    []string{"RUS"},
		AltNames: []string(nil),
		Tags:     []string{"russian"},
	},
	{
		Alpha3:   "MUR",
		Numeric:  "480",
		Symbol:   "₨",
		Name:     "Mauritius Rupee",
		Accuracy: 2,
		Users:    []string{"MUS"},
		AltNames: []string(nil),
		Tags:     []string{"mauritius"},
	},
	{
		Alpha3:   "PEN",
		Numeric:  "604",
		Symbol:   "S/.",
		Name:     "Sol",
		Accuracy: 2,
		Users:    []string{"PER"},
		AltNames: []string(nil),
		Tags:     []string{"sol"},
	},
	{
		Alpha3:   "UYU",
		Numeric:  "858",
		Symbol:   "$U",
		Name:     "Peso Uruguayo",
		Accuracy: 2,
		Users:    []string{"URY"},
		AltNames: []string(nil),
		Tags:     []string{"uruguayo"},
	},
	{
		Alpha3:   "AOA",
		Numeric:  "973",
		Symbol:   "Kz",
		Name:     "Kwanza",
		Accuracy: 2,
		Users:    []string{"AGO"},
		AltNames: []string(nil),
		Tags:     []string{"kwanza"},
	},
	{
		Alpha3:   "BHD",
		Numeric:  "048",
		Symbol:   ".د.ب",
		Name:     "Bahraini Dinar",
		Accuracy: 3,
		Users:    []string{"BHR"},
		AltNames: []string(nil),
		Tags:     []string{"bahraini"},
	},
	{
		Alpha3:   "BAM",
		Numeric:  "977",
		Symbol:   "KM",
		Name:     "Convertible Mark",
		Accuracy: 2,
		Users:    []string{"BIH"},
		AltNames: []string(nil),
		Tags:     []string{"mark"},
	},
	{
		Alpha3:   "IQD",
		Numeric:  "368",
		Symbol:   "ع.د",
		Name:     "Iraqi Dinar",
		Accuracy: 3,
		Users:    []string{"IRQ"},
		AltNames: []string(nil),
		Tags:     []string{"iraqi"},
	},
	{
		Alpha3:   "TWD",
		Numeric:  "901",
		Symbol:   "NT$",
		Name:     "New Taiwan Dollar",
		Accuracy: 2,
		Users:    []string{"TWN"},
		AltNames: []string(nil),
		Tags:     []string{"taiwan"},
	},
	{
		Alpha3:   "ALL",
		Numeric:  "008",
		Symbol:   "Lek",
		Name:     "Lek",
		Accuracy: 2,
		Users:    []string{"ALB"},
		AltNames: []string(nil),
		Tags:     []string{"lek"},
	},
	{
		Alpha3:   "CDF",
		Numeric:  "976",
		Symbol:   "FC",
		Name:     "Congolese Franc",
		Accuracy: 2,
		Users:    []string{"COD"},
		AltNames: []string(nil),
		Tags:     []string{"congolese"},
	},
	{
		Alpha3:   "HRK",
		Numeric:  "191",
		Symbol:   "kn",
		Name:     "Kuna",
		Accuracy: 2,
		Users:    []string{"HRV"},
		AltNames: []string(nil),
		Tags:     []string{"kuna"},
	},
	{
		Alpha3:   "SZL",
		Numeric:  "748",
		Symbol:   "E",
		Name:     "Lilangeni",
		Accuracy: 2,
		Users:    []string{"SWZ"},
		AltNames: []string(nil),
		Tags:     []string{"lilangeni"},
	},
	{
		Alpha3:   "ZAR",
		Numeric:  "710",
		Symbol:   "R",
		Name:     "Rand",
		Accuracy: 2,
		Users:    []string{"ZWE", "ZAF", "LSO", "NAM"},
		AltNames: []string(nil),
		Tags:     []string{"rand"},
	},
	{
		Alpha3:   "NPR",
		Numeric:  "524",
		Symbol:   "₨",
		Name:     "Nepalese Rupee",
		Accuracy: 2,
		Users:    []string{"NPL"},
		AltNames: []string(nil),
		Tags:     []string{"nepalese"},
	},
	{
		Alpha3:   "SBD",
		Numeric:  "090",
		Symbol:   "$",
		Name:     "Solomon Islands Dollar",
		Accuracy: 2,
		Users:    []string{"SLB"},
		AltNames: []string(nil),
		Tags:     []string{"solomon"},
	},
	{
		Alpha3:   "ZMW",
		Numeric:  "967",
		Symbol:   "",
		Name:     "Zambian Kwacha",
		Accuracy: 2,
		Users:    []string{"ZMB"},
		AltNames: []string(nil),
		Tags:     []string{"zambian"},
	},
	{
		Alpha3:   "SLL",
		Numeric:  "694",
		Symbol:   "Le",
		Name:     "Leone",
		Accuracy: 2,
		Users:    []string{"SLE"},
		AltNames: []string(nil),
		Tags:     []string{"leone"},
	},
	{
		Alpha3:   "AED",
		Numeric:  "784",
		Symbol:   "د.إ",
		Name:     "UAE Dirham",
		Accuracy: 2,
		Users:    []string{"ARE"},
		AltNames: []string(nil),
		Tags:     []string{"uae"},
	},
	{
		Alpha3:   "UYI",
		Numeric:  "940",
		Symbol:   "",
		Name:     "Uruguay Peso en Unidades Indexadas (UI)",
		Accuracy: 0,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"indexadas", "uruguay", "ui", "en", "unidades"},
	},
	{
		Alpha3:   "BOB",
		Numeric:  "068",
		Symbol:   "$b",
		Name:     "Boliviano",
		Accuracy: 2,
		Users:    []string{"BOL"},
		AltNames: []string(nil),
		Tags:     []string{"boliviano"},
	},
	{
		Alpha3:   "CVE",
		Numeric:  "132",
		Symbol:   "$",
		Name:     "Cabo Verde Escudo",
		Accuracy: 2,
		Users:    []string{"CPV"},
		AltNames: []string(nil),
		Tags:     []string{"verde", "escudo", "cabo"},
	},
	{
		Alpha3:   "KRW",
		Numeric:  "410",
		Symbol:   "₩",
		Name:     "Won",
		Accuracy: 0,
		Users:    []string{"KOR"},
		AltNames: []string(nil),
		Tags:     []string{},
	},
	{
		Alpha3:   "MXV",
		Numeric:  "979",
		Symbol:   "",
		Name:     "Mexican Unidad de Inversion (UDI)",
		Accuracy: 2,
		Users:    []string(nil),
		AltNames: []string(nil),
		Tags:     []string{"udi", "inversion"},
	},
	{
		Alpha3:   "NIO",
		Numeric:  "558",
		Symbol:   "C$",
		Name:     "Cordoba Oro",
		Accuracy: 2,
		Users:    []string{"NIC"},
		AltNames: []string(nil),
		Tags:     []string{"oro", "cordoba"},
	},
	{
		Alpha3:   "RWF",
		Numeric:  "646",
		Symbol:   "FRw",
		Name:     "Rwanda Franc",
		Accuracy: 0,
		Users:    []string{"RWA"},
		AltNames: []string(nil),
		Tags:     []string{"rwanda"},
	},
	{
		Alpha3:   "TMT",
		Numeric:  "934",
		Symbol:   "",
		Name:     "Turkmenistan New Manat",
		Accuracy: 2,
		Users:    []string{"TKM"},
		AltNames: []string(nil),
		Tags:     []string{"turkmenistan"},
	},
	{
		Alpha3:   "BGN",
		Numeric:  "975",
		Symbol:   "лв",
		Name:     "Bulgarian Lev",
		Accuracy: 2,
		Users:    []string{"BGR"},
		AltNames: []string(nil),
		Tags:     []string{"bulgarian", "lev"},
	},
	{
		Alpha3:   "TOP",
		Numeric:  "776",
		Symbol:   "T$",
		Name:     "Pa’anga",
		Accuracy: 2,
		Users:    []string{"TON"},
		AltNames: []string(nil),
		Tags:     []string{"pa", "anga"},
	},
	{
		Alpha3:   "BYN",
		Numeric:  "933",
		Symbol:   "",
		Name:     "Belarusian Ruble",
		Accuracy: 2,
		Users:    []string{"BLR"},
		AltNames: []string(nil),
		Tags:     []string{"belarusian"},
	},
	{
		Alpha3:   "XPF",
		Numeric:  "953",
		Symbol:   "",
		Name:     "CFP Franc",
		Accuracy: 0,
		Users:    []string{"PYF", "WLF", "NCL"},
		AltNames: []string(nil),
		Tags:     []string{"cfp"},
	},
	{
		Alpha3:   "GHS",
		Numeric:  "936",
		Symbol:   "",
		Name:     "Ghana Cedi",
		Accuracy: 2,
		Users:    []string{"GHA"},
		AltNames: []string(nil),
		Tags:     []string{"cedi", "ghana"},
	},
	{
		Alpha3:   "KES",
		Numeric:  "404",
		Symbol:   "KSh,",
		Name:     "Kenyan Shilling",
		Accuracy: 2,
		Users:    []string{"KEN"},
		AltNames: []string(nil),
		Tags:     []string{"kenyan"},
	},
	{
		Alpha3:   "KWD",
		Numeric:  "414",
		Symbol:   "د.ك",
		Name:     "Kuwaiti Dinar",
		Accuracy: 3,
		Users:    []string{"KWT"},
		AltNames: []string(nil),
		Tags:     []string{"kuwaiti"},
	},
	{
		Alpha3:   "RON",
		Numeric:  "946",
		Symbol:   "lei",
		Name:     "Romanian Leu",
		Accuracy: 2,
		Users:    []string{"ROU"},
		AltNames: []string(nil),
		Tags:     []string{"romanian"},
	},
	{
		Alpha3:   "THB",
		Numeric:  "764",
		Symbol:   "฿",
		Name:     "Baht",
		Accuracy: 2,
		Users:    []string{"THA"},
		AltNames: []string(nil),
		Tags:     []string{"baht"},
	},
}
