package currency

// Updated at: 2021-04-13 18:45:41.138063722 +0300 MSK m=+2.451309993
var List = []Currency{
	{Alpha3: "AMD", Numeric: "051", Symbol: "դր.", Name: "Armenian Dram", AltNames: []string(nil), Tags: []string{"dram", "armenian"}, Accuracy: 2, Users: []string{"ARM"}},
	{Alpha3: "BZD", Numeric: "084", Symbol: "BZ$", Name: "Belize Dollar", AltNames: []string(nil), Tags: []string{"belize"}, Accuracy: 2, Users: []string{"BLZ"}},
	{Alpha3: "COP", Numeric: "170", Symbol: "$", Name: "Colombian Peso", AltNames: []string(nil), Tags: []string{"colombian"}, Accuracy: 2, Users: []string{"COL"}},
	{Alpha3: "SZL", Numeric: "748", Symbol: "E", Name: "Lilangeni", AltNames: []string(nil), Tags: []string{"lilangeni"}, Accuracy: 2, Users: []string{"SWZ"}},
	{Alpha3: "MRU", Numeric: "929", Symbol: "", Name: "Ouguiya", AltNames: []string(nil), Tags: []string{"ouguiya"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "VND", Numeric: "704", Symbol: "₫", Name: "Dong", AltNames: []string(nil), Tags: []string{"dong"}, Accuracy: 0, Users: []string{"VNM"}},
	{Alpha3: "YER", Numeric: "886", Symbol: "﷼", Name: "Yemeni Rial", AltNames: []string(nil), Tags: []string{"yemeni"}, Accuracy: 2, Users: []string{"YEM"}},
	{Alpha3: "ARS", Numeric: "032", Symbol: "$", Name: "Argentine Peso", AltNames: []string(nil), Tags: []string{"argentine"}, Accuracy: 2, Users: []string{"ARG"}},
	{Alpha3: "CLF", Numeric: "990", Symbol: "", Name: "Unidad de Fomento", AltNames: []string(nil), Tags: []string{"fomento"}, Accuracy: 4, Users: []string(nil)},
	{Alpha3: "MKD", Numeric: "807", Symbol: "ден", Name: "Denar", AltNames: []string(nil), Tags: []string{"denar"}, Accuracy: 2, Users: []string{"MKD"}},
	{Alpha3: "MAD", Numeric: "504", Symbol: "DH", Name: "Moroccan Dirham", AltNames: []string(nil), Tags: []string{"moroccan"}, Accuracy: 2, Users: []string{"ESH", "MAR"}},
	{Alpha3: "ZMW", Numeric: "967", Symbol: "", Name: "Zambian Kwacha", AltNames: []string(nil), Tags: []string{"zambian"}, Accuracy: 2, Users: []string{"ZMB"}},
	{Alpha3: "BMD", Numeric: "060", Symbol: "", Name: "Bermudian Dollar", AltNames: []string(nil), Tags: []string{"bermudian"}, Accuracy: 2, Users: []string{"BMU"}},
	{Alpha3: "CUC", Numeric: "931", Symbol: "$", Name: "Peso Convertible", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string{"CUB"}},
	{Alpha3: "SCR", Numeric: "690", Symbol: "₨", Name: "Seychelles Rupee", AltNames: []string(nil), Tags: []string{"seychelles"}, Accuracy: 2, Users: []string{"SYC"}},
	{Alpha3: "AED", Numeric: "784", Symbol: "د.إ", Name: "UAE Dirham", AltNames: []string(nil), Tags: []string{"uae"}, Accuracy: 2, Users: []string{"ARE"}},
	{Alpha3: "CLP", Numeric: "152", Symbol: "$", Name: "Chilean Peso", AltNames: []string(nil), Tags: []string{"chilean"}, Accuracy: 0, Users: []string{"CHL"}},
	{Alpha3: "MDL", Numeric: "498", Symbol: "L", Name: "Moldovan Leu", AltNames: []string(nil), Tags: []string{"moldovan"}, Accuracy: 2, Users: []string{"MDA"}},
	{Alpha3: "AOA", Numeric: "973", Symbol: "Kz", Name: "Kwanza", AltNames: []string(nil), Tags: []string{"kwanza"}, Accuracy: 2, Users: []string{"AGO"}},
	{Alpha3: "HKD", Numeric: "344", Symbol: "", Name: "Hong Kong Dollar", AltNames: []string(nil), Tags: []string{"hong", "kong"}, Accuracy: 2, Users: []string{"HKG"}},
	{Alpha3: "LSL", Numeric: "426", Symbol: "L", Name: "Loti", AltNames: []string(nil), Tags: []string{"loti"}, Accuracy: 2, Users: []string{"LSO"}},
	{Alpha3: "MUR", Numeric: "480", Symbol: "₨", Name: "Mauritius Rupee", AltNames: []string(nil), Tags: []string{"mauritius"}, Accuracy: 2, Users: []string{"MUS"}},
	{Alpha3: "SYP", Numeric: "760", Symbol: "£", Name: "Syrian Pound", AltNames: []string(nil), Tags: []string{"syrian"}, Accuracy: 2, Users: []string{"SYR"}},
	{Alpha3: "DZD", Numeric: "012", Symbol: "", Name: "Algerian Dinar", AltNames: []string(nil), Tags: []string{"algerian"}, Accuracy: 2, Users: []string{"ESH", "DZA"}},
	{Alpha3: "TTD", Numeric: "780", Symbol: "TT$", Name: "Trinidad and Tobago Dollar", AltNames: []string(nil), Tags: []string{"and", "tobago", "trinidad"}, Accuracy: 2, Users: []string{"TTO"}},
	{Alpha3: "NGN", Numeric: "566", Symbol: "₦", Name: "Naira", AltNames: []string(nil), Tags: []string{"naira"}, Accuracy: 2, Users: []string{"NGA"}},
	{Alpha3: "CHW", Numeric: "948", Symbol: "", Name: "WIR Franc", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "TRY", Numeric: "949", Symbol: "₺", Name: "Turkish Lira", AltNames: []string(nil), Tags: []string{"lira", "turkish"}, Accuracy: 2, Users: []string{"TUR"}},
	{Alpha3: "UAH", Numeric: "980", Symbol: "₴", Name: "Hryvnia", AltNames: []string(nil), Tags: []string{"hryvnia"}, Accuracy: 2, Users: []string{"UKR"}},
	{Alpha3: "VUV", Numeric: "548", Symbol: "", Name: "Vatu", AltNames: []string(nil), Tags: []string{"vatu"}, Accuracy: 0, Users: []string{"VUT"}},
	{Alpha3: "ALL", Numeric: "008", Symbol: "Lek", Name: "Lek", AltNames: []string(nil), Tags: []string{"lek"}, Accuracy: 2, Users: []string{"ALB"}},
	{Alpha3: "BOV", Numeric: "984", Symbol: "", Name: "Mvdol", AltNames: []string(nil), Tags: []string{"mvdol"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "BGN", Numeric: "975", Symbol: "лв", Name: "Bulgarian Lev", AltNames: []string(nil), Tags: []string{"bulgarian", "lev"}, Accuracy: 2, Users: []string{"BGR"}},
	{Alpha3: "CRC", Numeric: "188", Symbol: "₡", Name: "Costa Rican Colon", AltNames: []string(nil), Tags: []string{"rican", "costa"}, Accuracy: 2, Users: []string{"CRI"}},
	{Alpha3: "KZT", Numeric: "398", Symbol: "лв", Name: "Tenge", AltNames: []string(nil), Tags: []string{"tenge"}, Accuracy: 2, Users: []string{"KAZ"}},
	{Alpha3: "MXV", Numeric: "979", Symbol: "", Name: "Mexican Unidad de Inversion (UDI)", AltNames: []string(nil), Tags: []string{"udi", "inversion"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "TZS", Numeric: "834", Symbol: "TSh", Name: "Tanzanian Shilling", AltNames: []string(nil), Tags: []string{"tanzanian"}, Accuracy: 2, Users: []string{"TZA"}},
	{Alpha3: "UGX", Numeric: "800", Symbol: "USh", Name: "Uganda Shilling", AltNames: []string(nil), Tags: []string{"uganda"}, Accuracy: 0, Users: []string{"UGA"}},
	{Alpha3: "INR", Numeric: "356", Symbol: "₹", Name: "Indian Rupee", AltNames: []string(nil), Tags: []string{"indian"}, Accuracy: 2, Users: []string{"ZWE", "IND", "BTN"}},
	{Alpha3: "HUF", Numeric: "348", Symbol: "Ft", Name: "Forint", AltNames: []string(nil), Tags: []string{"forint"}, Accuracy: 2, Users: []string{"HUN"}},
	{Alpha3: "SLL", Numeric: "694", Symbol: "Le", Name: "Leone", AltNames: []string(nil), Tags: []string{"leone"}, Accuracy: 2, Users: []string{"SLE"}},
	{Alpha3: "USN", Numeric: "997", Symbol: "", Name: "US Dollar (Next day)", AltNames: []string(nil), Tags: []string{"next", "day"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "BTN", Numeric: "064", Symbol: "Nu.", Name: "Ngultrum", AltNames: []string(nil), Tags: []string{"ngultrum"}, Accuracy: 2, Users: []string{"BTN"}},
	{Alpha3: "ZAR", Numeric: "710", Symbol: "R", Name: "Rand", AltNames: []string(nil), Tags: []string{"rand"}, Accuracy: 2, Users: []string{"ZWE", "ZAF", "LSO", "NAM"}},
	{Alpha3: "PKR", Numeric: "586", Symbol: "₨", Name: "Pakistan Rupee", AltNames: []string(nil), Tags: []string{"pakistan"}, Accuracy: 2, Users: []string{"PAK"}},
	{Alpha3: "QAR", Numeric: "634", Symbol: "﷼", Name: "Qatari Rial", AltNames: []string(nil), Tags: []string{"qatari"}, Accuracy: 2, Users: []string{"QAT"}},
	{Alpha3: "EUR", Numeric: "978", Symbol: "€", Name: "Euro", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string{"ITA", "KOS", "ZWE", "ALA", "MTQ", "BEL", "SVK", "NLD", "EST", "SVN", "CYP", "MNE", "LTU", "FIN", "MCO", "MAF", "LVA", "AND", "IRL", "ATF", "MYT", "GRC", "LUX", "FRA", "BLM", "SPM", "GUF", "AUT", "DEU", "GLP", "MLT", "PRT", "REU", "VAT", "ESP", "SMR"}},
	{Alpha3: "IQD", Numeric: "368", Symbol: "ع.د", Name: "Iraqi Dinar", AltNames: []string(nil), Tags: []string{"iraqi"}, Accuracy: 3, Users: []string{"IRQ"}},
	{Alpha3: "PAB", Numeric: "590", Symbol: "B/.", Name: "Balboa", AltNames: []string(nil), Tags: []string{"balboa"}, Accuracy: 2, Users: []string{"PAN"}},
	{Alpha3: "BIF", Numeric: "108", Symbol: "FBu", Name: "Burundi Franc", AltNames: []string(nil), Tags: []string{"burundi"}, Accuracy: 0, Users: []string{"BDI"}},
	{Alpha3: "CVE", Numeric: "132", Symbol: "$", Name: "Cabo Verde Escudo", AltNames: []string(nil), Tags: []string{"verde", "escudo", "cabo"}, Accuracy: 2, Users: []string{"CPV"}},
	{Alpha3: "DJF", Numeric: "262", Symbol: "Fdj", Name: "Djibouti Franc", AltNames: []string(nil), Tags: []string{"djibouti"}, Accuracy: 0, Users: []string{"DJI"}},
	{Alpha3: "ETB", Numeric: "230", Symbol: "ብር", Name: "Ethiopian Birr", AltNames: []string(nil), Tags: []string{"birr", "ethiopian"}, Accuracy: 2, Users: []string{"ETH"}},
	{Alpha3: "GIP", Numeric: "292", Symbol: "", Name: "Gibraltar Pound", AltNames: []string(nil), Tags: []string{"gibraltar"}, Accuracy: 2, Users: []string{"GIB"}},
	{Alpha3: "KGS", Numeric: "417", Symbol: "лв", Name: "Som", AltNames: []string(nil), Tags: []string{"som"}, Accuracy: 2, Users: []string{"KGZ"}},
	{Alpha3: "LRD", Numeric: "430", Symbol: "$", Name: "Liberian Dollar", AltNames: []string(nil), Tags: []string{"liberian"}, Accuracy: 2, Users: []string{"LBR"}},
	{Alpha3: "SAR", Numeric: "682", Symbol: "﷼", Name: "Saudi Riyal", AltNames: []string(nil), Tags: []string{"riyal", "saudi"}, Accuracy: 2, Users: []string{"SAU"}},
	{Alpha3: "BBD", Numeric: "052", Symbol: "$", Name: "Barbados Dollar", AltNames: []string(nil), Tags: []string{"barbados"}, Accuracy: 2, Users: []string{"BRB"}},
	{Alpha3: "UYI", Numeric: "940", Symbol: "", Name: "Uruguay Peso en Unidades Indexadas (UI)", AltNames: []string(nil), Tags: []string{"en", "ui", "indexadas", "unidades", "uruguay"}, Accuracy: 0, Users: []string(nil)},
	{Alpha3: "TMT", Numeric: "934", Symbol: "", Name: "Turkmenistan New Manat", AltNames: []string(nil), Tags: []string{"turkmenistan"}, Accuracy: 2, Users: []string{"TKM"}},
	{Alpha3: "BDT", Numeric: "050", Symbol: "৳", Name: "Taka", AltNames: []string(nil), Tags: []string{"taka"}, Accuracy: 2, Users: []string{"BGD"}},
	{Alpha3: "BOB", Numeric: "068", Symbol: "$b", Name: "Boliviano", AltNames: []string(nil), Tags: []string{"boliviano"}, Accuracy: 2, Users: []string{"BOL"}},
	{Alpha3: "KYD", Numeric: "136", Symbol: "", Name: "Cayman Islands Dollar", AltNames: []string(nil), Tags: []string{"cayman"}, Accuracy: 2, Users: []string{"CYM"}},
	{Alpha3: "MOP", Numeric: "446", Symbol: "", Name: "Pataca", AltNames: []string(nil), Tags: []string{"pataca"}, Accuracy: 2, Users: []string{"MAC"}},
	{Alpha3: "BSD", Numeric: "044", Symbol: "$", Name: "Bahamian Dollar", AltNames: []string(nil), Tags: []string{"bahamian"}, Accuracy: 2, Users: []string{"BHS"}},
	{Alpha3: "ERN", Numeric: "232", Symbol: "ናቕፋ", Name: "Nakfa", AltNames: []string(nil), Tags: []string{"nakfa"}, Accuracy: 2, Users: []string{"ERI"}},
	{Alpha3: "GTQ", Numeric: "320", Symbol: "Q", Name: "Quetzal", AltNames: []string(nil), Tags: []string{"quetzal"}, Accuracy: 2, Users: []string{"GTM"}},
	{Alpha3: "MZN", Numeric: "943", Symbol: "MT", Name: "Mozambique Metical", AltNames: []string(nil), Tags: []string{"mozambique", "metical"}, Accuracy: 2, Users: []string{"MOZ"}},
	{Alpha3: "MMK", Numeric: "104", Symbol: "K", Name: "Kyat", AltNames: []string(nil), Tags: []string{"kyat"}, Accuracy: 2, Users: []string{"MMR"}},
	{Alpha3: "SRD", Numeric: "968", Symbol: "$", Name: "Surinam Dollar", AltNames: []string(nil), Tags: []string{"surinam"}, Accuracy: 2, Users: []string{"SUR"}},
	{Alpha3: "UZS", Numeric: "860", Symbol: "лв", Name: "Uzbekistan Sum", AltNames: []string(nil), Tags: []string{"sum", "uzbekistan"}, Accuracy: 2, Users: []string{"UZB"}},
	{Alpha3: "HRK", Numeric: "191", Symbol: "kn", Name: "Kuna", AltNames: []string(nil), Tags: []string{"kuna"}, Accuracy: 2, Users: []string{"HRV"}},
	{Alpha3: "KPW", Numeric: "408", Symbol: "₩", Name: "North Korean Won", AltNames: []string(nil), Tags: []string{"korean", "north"}, Accuracy: 2, Users: []string{"PRK"}},
	{Alpha3: "CHF", Numeric: "756", Symbol: "CHF", Name: "Swiss Franc", AltNames: []string(nil), Tags: []string{"swiss"}, Accuracy: 2, Users: []string{"LIE", "CHE"}},
	{Alpha3: "MGA", Numeric: "969", Symbol: "Ar", Name: "Malagasy Ariary", AltNames: []string(nil), Tags: []string{"ariary", "malagasy"}, Accuracy: 2, Users: []string{"MDG"}},
	{Alpha3: "MVR", Numeric: "462", Symbol: "Rf", Name: "Rufiyaa", AltNames: []string(nil), Tags: []string{"rufiyaa"}, Accuracy: 2, Users: []string{"MDV"}},
	{Alpha3: "HNL", Numeric: "340", Symbol: "L", Name: "Lempira", AltNames: []string(nil), Tags: []string{"lempira"}, Accuracy: 2, Users: []string{"HND"}},
	{Alpha3: "EGP", Numeric: "818", Symbol: "£", Name: "Egyptian Pound", AltNames: []string(nil), Tags: []string{"egyptian"}, Accuracy: 2, Users: []string{"EGY"}},
	{Alpha3: "BWP", Numeric: "072", Symbol: "P", Name: "Pula", AltNames: []string(nil), Tags: []string{"pula"}, Accuracy: 2, Users: []string{"ZWE", "BWA"}},
	{Alpha3: "XAF", Numeric: "950", Symbol: "FCFA", Name: "CFA Franc BEAC", AltNames: []string(nil), Tags: []string{"beac"}, Accuracy: 0, Users: []string{"CAF", "TCD", "GNQ", "COG", "CMR", "GAB"}},
	{Alpha3: "COU", Numeric: "970", Symbol: "", Name: "Unidad de Valor Real", AltNames: []string(nil), Tags: []string{"valor"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "NZD", Numeric: "554", Symbol: "$", Name: "New Zealand Dollar", AltNames: []string(nil), Tags: []string{"zealand"}, Accuracy: 2, Users: []string{"COK", "NIU", "PCN", "NZL", "TKL"}},
	{Alpha3: "GMD", Numeric: "270", Symbol: "D", Name: "Dalasi", AltNames: []string(nil), Tags: []string{"dalasi"}, Accuracy: 2, Users: []string{"GMB"}},
	{Alpha3: "STN", Numeric: "930", Symbol: "", Name: "Dobra", AltNames: []string(nil), Tags: []string{"dobra"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "BAM", Numeric: "977", Symbol: "KM", Name: "Convertible Mark", AltNames: []string(nil), Tags: []string{"mark"}, Accuracy: 2, Users: []string{"BIH"}},
	{Alpha3: "JOD", Numeric: "400", Symbol: "د.ا", Name: "Jordanian Dinar", AltNames: []string(nil), Tags: []string{"jordanian"}, Accuracy: 3, Users: []string{"JOR"}},
	{Alpha3: "MYR", Numeric: "458", Symbol: "RM", Name: "Malaysian Ringgit", AltNames: []string(nil), Tags: []string{"ringgit", "malaysian"}, Accuracy: 2, Users: []string{"MYS"}},
	{Alpha3: "PYG", Numeric: "600", Symbol: "Gs", Name: "Guarani", AltNames: []string(nil), Tags: []string{"guarani"}, Accuracy: 0, Users: []string{"PRY"}},
	{Alpha3: "THB", Numeric: "764", Symbol: "฿", Name: "Baht", AltNames: []string(nil), Tags: []string{"baht"}, Accuracy: 2, Users: []string{"THA"}},
	{Alpha3: "CNY", Numeric: "156", Symbol: "¥", Name: "Yuan Renminbi", AltNames: []string(nil), Tags: []string{"renminbi", "yuan"}, Accuracy: 2, Users: []string{"ZWE", "CHN"}},
	{Alpha3: "FJD", Numeric: "242", Symbol: "$", Name: "Fiji Dollar", AltNames: []string(nil), Tags: []string{"fiji"}, Accuracy: 2, Users: []string{"FJI"}},
	{Alpha3: "GHS", Numeric: "936", Symbol: "", Name: "Ghana Cedi", AltNames: []string(nil), Tags: []string{"cedi", "ghana"}, Accuracy: 2, Users: []string{"GHA"}},
	{Alpha3: "GYD", Numeric: "328", Symbol: "$", Name: "Guyana Dollar", AltNames: []string(nil), Tags: []string{"guyana"}, Accuracy: 2, Users: []string{"GUY"}},
	{Alpha3: "PGK", Numeric: "598", Symbol: "K", Name: "Kina", AltNames: []string(nil), Tags: []string{"kina"}, Accuracy: 2, Users: []string{"PNG"}},
	{Alpha3: "SGD", Numeric: "702", Symbol: "$", Name: "Singapore Dollar", AltNames: []string(nil), Tags: []string{"singapore"}, Accuracy: 2, Users: []string{"BRN", "SGP"}},
	{Alpha3: "SDG", Numeric: "938", Symbol: "SD", Name: "Sudanese Pound", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string{"SDN"}},
	{Alpha3: "BND", Numeric: "096", Symbol: "$", Name: "Brunei Dollar", AltNames: []string(nil), Tags: []string{"brunei"}, Accuracy: 2, Users: []string{"BRN", "SGP"}},
	{Alpha3: "NIO", Numeric: "558", Symbol: "C$", Name: "Cordoba Oro", AltNames: []string(nil), Tags: []string{"cordoba", "oro"}, Accuracy: 2, Users: []string{"NIC"}},
	{Alpha3: "UYU", Numeric: "858", Symbol: "$U", Name: "Peso Uruguayo", AltNames: []string(nil), Tags: []string{"uruguayo"}, Accuracy: 2, Users: []string{"URY"}},
	{Alpha3: "LYD", Numeric: "434", Symbol: "ل.د", Name: "Libyan Dinar", AltNames: []string(nil), Tags: []string{"libyan"}, Accuracy: 3, Users: []string{"LBY"}},
	{Alpha3: "SHP", Numeric: "654", Symbol: "", Name: "Saint Helena Pound", AltNames: []string(nil), Tags: []string{"saint", "helena"}, Accuracy: 2, Users: []string{"SHN"}},
	{Alpha3: "CHE", Numeric: "947", Symbol: "", Name: "WIR Euro", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "ZWL", Numeric: "932", Symbol: "", Name: "Zimbabwe Dollar", AltNames: []string(nil), Tags: []string{"zimbabwe"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "OMR", Numeric: "512", Symbol: "﷼", Name: "Rial Omani", AltNames: []string(nil), Tags: []string{"omani"}, Accuracy: 3, Users: []string{"OMN"}},
	{Alpha3: "CAD", Numeric: "124", Symbol: "$", Name: "Canadian Dollar", AltNames: []string(nil), Tags: []string{"canadian"}, Accuracy: 2, Users: []string{"CAN"}},
	{Alpha3: "SSP", Numeric: "728", Symbol: "£", Name: "South Sudanese Pound", AltNames: []string(nil), Tags: []string{"south"}, Accuracy: 2, Users: []string{"SSD"}},
	{Alpha3: "TWD", Numeric: "901", Symbol: "NT$", Name: "New Taiwan Dollar", AltNames: []string(nil), Tags: []string{"taiwan"}, Accuracy: 2, Users: []string{"TWN"}},
	{Alpha3: "TND", Numeric: "788", Symbol: "د.ت", Name: "Tunisian Dinar", AltNames: []string(nil), Tags: []string{"tunisian"}, Accuracy: 3, Users: []string{"TUN"}},
	{Alpha3: "VES", Numeric: "928", Symbol: "", Name: "Bolívar Soberano", AltNames: []string(nil), Tags: []string{"soberano", "bolívar"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "AWG", Numeric: "533", Symbol: "", Name: "Aruban Florin", AltNames: []string(nil), Tags: []string{"aruban", "florin"}, Accuracy: 2, Users: []string{"ABW"}},
	{Alpha3: "NAD", Numeric: "516", Symbol: "$", Name: "Namibia Dollar", AltNames: []string(nil), Tags: []string{"namibia"}, Accuracy: 2, Users: []string{"NAM"}},
	{Alpha3: "TJS", Numeric: "972", Symbol: "ЅM", Name: "Somoni", AltNames: []string(nil), Tags: []string{"somoni"}, Accuracy: 2, Users: []string{"TJK"}},
	{Alpha3: "ISK", Numeric: "352", Symbol: "kr", Name: "Iceland Krona", AltNames: []string(nil), Tags: []string{"iceland"}, Accuracy: 0, Users: []string{"ISL"}},
	{Alpha3: "GNF", Numeric: "324", Symbol: "FG", Name: "Guinean Franc", AltNames: []string(nil), Tags: []string{"guinean"}, Accuracy: 0, Users: []string{"GIN"}},
	{Alpha3: "AZN", Numeric: "944", Symbol: "₼", Name: "Azerbaijan Manat", AltNames: []string(nil), Tags: []string{"azerbaijan"}, Accuracy: 2, Users: []string{"AZE"}},
	{Alpha3: "KHR", Numeric: "116", Symbol: "៛", Name: "Riel", AltNames: []string(nil), Tags: []string{"riel"}, Accuracy: 2, Users: []string{"KHM"}},
	{Alpha3: "CZK", Numeric: "203", Symbol: "Kč", Name: "Czech Koruna", AltNames: []string(nil), Tags: []string{"koruna", "czech"}, Accuracy: 2, Users: []string{"CZE"}},
	{Alpha3: "FKP", Numeric: "238", Symbol: "", Name: "Falkland Islands Pound", AltNames: []string(nil), Tags: []string{"falkland"}, Accuracy: 2, Users: []string{"FLK"}},
	{Alpha3: "GEL", Numeric: "981", Symbol: "ლ", Name: "Lari", AltNames: []string(nil), Tags: []string{"lari"}, Accuracy: 2, Users: []string{"GEO"}},
	{Alpha3: "KWD", Numeric: "414", Symbol: "د.ك", Name: "Kuwaiti Dinar", AltNames: []string(nil), Tags: []string{"kuwaiti"}, Accuracy: 3, Users: []string{"KWT"}},
	{Alpha3: "LBP", Numeric: "422", Symbol: "£", Name: "Lebanese Pound", AltNames: []string(nil), Tags: []string{"lebanese"}, Accuracy: 2, Users: []string{"LBN"}},
	{Alpha3: "USD", Numeric: "840", Symbol: "$", Name: "US Dollar", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string{"VIR", "ZWE", "MHL", "PAN", "VGB", "BES", "SLV", "FSM", "ECU", "MNP", "USA", "GUM", "PRI", "PLW", "ASM", "TCA", "IOT", "TLS", "KHM"}},
	{Alpha3: "PHP", Numeric: "608", Symbol: "₱", Name: "Philippine Peso", AltNames: []string(nil), Tags: []string{"philippine"}, Accuracy: 2, Users: []string{"PHL"}},
	{Alpha3: "PLN", Numeric: "985", Symbol: "zł", Name: "Zloty", AltNames: []string(nil), Tags: []string{"zloty"}, Accuracy: 2, Users: []string{"POL"}},
	{Alpha3: "RUB", Numeric: "643", Symbol: "₽", Name: "Russian Ruble", AltNames: []string(nil), Tags: []string{"russian"}, Accuracy: 2, Users: []string{"RUS"}},
	{Alpha3: "SOS", Numeric: "706", Symbol: "S", Name: "Somali Shilling", AltNames: []string(nil), Tags: []string{"somali"}, Accuracy: 2, Users: []string{"SOM"}},
	{Alpha3: "TOP", Numeric: "776", Symbol: "T$", Name: "Pa’anga", AltNames: []string(nil), Tags: []string{"anga", "pa"}, Accuracy: 2, Users: []string{"TON"}},
	{Alpha3: "MXN", Numeric: "484", Symbol: "$", Name: "Mexican Peso", AltNames: []string(nil), Tags: []string{}, Accuracy: 2, Users: []string{"MEX"}},
	{Alpha3: "XCD", Numeric: "951", Symbol: "$", Name: "East Caribbean Dollar", AltNames: []string(nil), Tags: []string{"caribbean", "east"}, Accuracy: 2, Users: []string{"GRD", "VCT", "KNA", "AIA", "ATG", "MSR", "DMA", "LCA"}},
	{Alpha3: "BRL", Numeric: "986", Symbol: "R$", Name: "Brazilian Real", AltNames: []string(nil), Tags: []string{"brazilian"}, Accuracy: 2, Users: []string{"BRA"}},
	{Alpha3: "IDR", Numeric: "360", Symbol: "Rp", Name: "Rupiah", AltNames: []string(nil), Tags: []string{"rupiah"}, Accuracy: 2, Users: []string{"IDN"}},
	{Alpha3: "NPR", Numeric: "524", Symbol: "₨", Name: "Nepalese Rupee", AltNames: []string(nil), Tags: []string{"nepalese"}, Accuracy: 2, Users: []string{"NPL"}},
	{Alpha3: "RWF", Numeric: "646", Symbol: "FRw", Name: "Rwanda Franc", AltNames: []string(nil), Tags: []string{"rwanda"}, Accuracy: 0, Users: []string{"RWA"}},
	{Alpha3: "SBD", Numeric: "090", Symbol: "$", Name: "Solomon Islands Dollar", AltNames: []string(nil), Tags: []string{"solomon"}, Accuracy: 2, Users: []string{"SLB"}},
	{Alpha3: "AFN", Numeric: "971", Symbol: "؋", Name: "Afghani", AltNames: []string(nil), Tags: []string{"afghani"}, Accuracy: 2, Users: []string{"AFG"}},
	{Alpha3: "DOP", Numeric: "214", Symbol: "RD$", Name: "Dominican Peso", AltNames: []string(nil), Tags: []string{"dominican"}, Accuracy: 2, Users: []string{"DOM"}},
	{Alpha3: "SVC", Numeric: "222", Symbol: "", Name: "El Salvador Colon", AltNames: []string(nil), Tags: []string{"salvador", "el"}, Accuracy: 2, Users: []string(nil)},
	{Alpha3: "XPF", Numeric: "953", Symbol: "", Name: "CFP Franc", AltNames: []string(nil), Tags: []string{"cfp"}, Accuracy: 0, Users: []string{"PYF", "WLF", "NCL"}},
	{Alpha3: "RON", Numeric: "946", Symbol: "lei", Name: "Romanian Leu", AltNames: []string(nil), Tags: []string{"romanian"}, Accuracy: 2, Users: []string{"ROU"}},
	{Alpha3: "WST", Numeric: "882", Symbol: "WS$", Name: "Tala", AltNames: []string(nil), Tags: []string{"tala"}, Accuracy: 2, Users: []string{"WSM"}},
	{Alpha3: "RSD", Numeric: "941", Symbol: "Дин.", Name: "Serbian Dinar", AltNames: []string(nil), Tags: []string{"serbian"}, Accuracy: 2, Users: []string{"SRB"}},
	{Alpha3: "KMF", Numeric: "174", Symbol: "CF", Name: "Comorian Franc", AltNames: []string(nil), Tags: []string{"comorian"}, Accuracy: 0, Users: []string{"COM"}},
	{Alpha3: "JPY", Numeric: "392", Symbol: "¥", Name: "Yen", AltNames: []string(nil), Tags: []string{"yen"}, Accuracy: 0, Users: []string{"ZWE", "JPN"}},
	{Alpha3: "LAK", Numeric: "418", Symbol: "₭", Name: "Lao Kip", AltNames: []string(nil), Tags: []string{"kip", "lao"}, Accuracy: 2, Users: []string{"LAO"}},
	{Alpha3: "LKR", Numeric: "144", Symbol: "₨", Name: "Sri Lanka Rupee", AltNames: []string(nil), Tags: []string{"lanka", "sri"}, Accuracy: 2, Users: []string{"LKA"}},
	{Alpha3: "DKK", Numeric: "208", Symbol: "kr.", Name: "Danish Krone", AltNames: []string(nil), Tags: []string{"danish"}, Accuracy: 2, Users: []string{"GRL", "DNK", "FRO"}},
	{Alpha3: "BHD", Numeric: "048", Symbol: ".د.ب", Name: "Bahraini Dinar", AltNames: []string(nil), Tags: []string{"bahraini"}, Accuracy: 3, Users: []string{"BHR"}},
	{Alpha3: "NOK", Numeric: "578", Symbol: "kr", Name: "Norwegian Krone", AltNames: []string(nil), Tags: []string{"norwegian"}, Accuracy: 2, Users: []string{"BVT", "NOR", "SJM"}},
	{Alpha3: "GBP", Numeric: "826", Symbol: "£", Name: "Pound Sterling", AltNames: []string(nil), Tags: []string{"sterling"}, Accuracy: 2, Users: []string{"ZWE", "SGS", "ATA", "GBR", "IMN", "JEY", "GGY"}},
	{Alpha3: "MWK", Numeric: "454", Symbol: "MK", Name: "Malawi Kwacha", AltNames: []string(nil), Tags: []string{"malawi"}, Accuracy: 2, Users: []string{"MWI"}},
	{Alpha3: "MNT", Numeric: "496", Symbol: "₮", Name: "Tugrik", AltNames: []string(nil), Tags: []string{"tugrik"}, Accuracy: 2, Users: []string{"MNG"}},
	{Alpha3: "UYW", Numeric: "927", Symbol: "", Name: "Unidad Previsional", AltNames: []string(nil), Tags: []string{"previsional"}, Accuracy: 4, Users: []string(nil)},
	{Alpha3: "AUD", Numeric: "036", Symbol: "$", Name: "Australian Dollar", AltNames: []string(nil), Tags: []string{"australian"}, Accuracy: 2, Users: []string{"ATA", "TUV", "CCK", "NRU", "CXR", "HMD", "KIR", "AUS", "NFK"}},
	{Alpha3: "XOF", Numeric: "952", Symbol: "CFA", Name: "CFA Franc BCEAO", AltNames: []string(nil), Tags: []string{"bceao"}, Accuracy: 0, Users: []string{"NER", "MLI", "CIV", "TGO", "BFA", "BEN", "SEN", "GNB"}},
	{Alpha3: "CUP", Numeric: "192", Symbol: "", Name: "Cuban Peso", AltNames: []string(nil), Tags: []string{"cuban"}, Accuracy: 2, Users: []string{"CUB"}},
	{Alpha3: "ANG", Numeric: "532", Symbol: "", Name: "Netherlands Antillean Guilder", AltNames: []string(nil), Tags: []string{"antillean", "netherlands", "guilder"}, Accuracy: 2, Users: []string{"SXM", "CUW"}},
	{Alpha3: "HTG", Numeric: "332", Symbol: "G", Name: "Gourde", AltNames: []string(nil), Tags: []string{"gourde"}, Accuracy: 2, Users: []string{"HTI"}},
	{Alpha3: "IRR", Numeric: "364", Symbol: "﷼", Name: "Iranian Rial", AltNames: []string(nil), Tags: []string{"iranian"}, Accuracy: 2, Users: []string{"IRN"}},
	{Alpha3: "JMD", Numeric: "388", Symbol: "J$", Name: "Jamaican Dollar", AltNames: []string(nil), Tags: []string{"jamaican"}, Accuracy: 2, Users: []string{"JAM"}},
	{Alpha3: "KES", Numeric: "404", Symbol: "KSh,", Name: "Kenyan Shilling", AltNames: []string(nil), Tags: []string{"kenyan"}, Accuracy: 2, Users: []string{"KEN"}},
	{Alpha3: "BYN", Numeric: "933", Symbol: "", Name: "Belarusian Ruble", AltNames: []string(nil), Tags: []string{"belarusian"}, Accuracy: 2, Users: []string{"BLR"}},
	{Alpha3: "PEN", Numeric: "604", Symbol: "S/.", Name: "Sol", AltNames: []string(nil), Tags: []string{"sol"}, Accuracy: 2, Users: []string{"PER"}},
	{Alpha3: "SEK", Numeric: "752", Symbol: "kr", Name: "Swedish Krona", AltNames: []string(nil), Tags: []string{"swedish"}, Accuracy: 2, Users: []string{"SWE"}},
	{Alpha3: "KRW", Numeric: "410", Symbol: "₩", Name: "Won", AltNames: []string(nil), Tags: []string{}, Accuracy: 0, Users: []string{"KOR"}},
	{Alpha3: "ILS", Numeric: "376", Symbol: "₪", Name: "New Israeli Sheqel", AltNames: []string(nil), Tags: []string{"israeli", "sheqel"}, Accuracy: 2, Users: []string{"ISR", "PSE"}},
	{Alpha3: "CDF", Numeric: "976", Symbol: "FC", Name: "Congolese Franc", AltNames: []string(nil), Tags: []string{"congolese"}, Accuracy: 2, Users: []string{"COD"}},
}
